var ImageLoader=function(s,m,D,h){function v(i,m){i.style["-webkit-transition"]=m;i.style["-moz-transition"]=m;i.style["-ms-transition"]=m;i.style["-o-transition"]=m;i.style.transition=m}function o(i,h,k,t){function o(){d||(d=!0,z[h]=!0,i.src=h,i.style.opacity="1",setTimeout(function(){v(i,"");setTimeout(function(){i.style.opacity=e.opacity;i.style["-webkit-transition"]=e["-webkit-transition"];i.style["-moz-transition"]=e["-moz-transition"];i.style["-ms-transition"]=e["-ms-transition"];i.style["-o-transition"]=
e["-o-transition"];i.style.transition=e.transition;t()},0)},y),m.body.removeChild(l))}var g;a:if(i){try{g=i instanceof Node||i instanceof HTMLElement;break a}catch(L){}g="object"!==typeof i||"number"!==typeof i.nodeType||"string"!==typeof i.nodeName?!1:!0}else g=!1;if(!g)throw TypeError("image must be a DOM element, got "+i);if("string"!==typeof h)throw TypeError("url must be a string, got "+h);switch(typeof k){case "function":t=k;case "undefined":k=0;case "number":break;default:throw TypeError("minimum wait time must be a number if deinfed, got "+
k);}switch(typeof t){case "undefined":t=function(){};case "function":break;default:throw TypeError("callback must be a function if defined, got "+t);}if(!0===z[h])i.src=h;else{var d=!1,a=+new Date+(k||0),e={opacity:i.style.opacity,"-webkit-transition":i.style["-webkit-transition"],"-moz-transition":i.style["-moz-transition"],"-ms-transition":i.style["-ms-transition"],"-o-transition":i.style["-o-transition"],transition:i.style.transition};i.style.opacity="0";setTimeout(function(){v(i,"opacity "+y/
1E3+"s ease-in-out")},0);var l=new Image;l.style.opacity="0";l.style.position="fixed";l.style.top="-100%";l.style.left="-100%";l.style.height="1px";l.style.width="1px";m.body.appendChild(l);l.onload=function(){var d=+new Date;d>=a?o():setTimeout(o,a-d)};l.onerror=l.onload;l.src=h}}var y=300,z={};D&&D.extend(D.fn,{imageLoader:function(i,m,h){this.forEach(function(t){o(t,i,m,h)});return this}});h&&(h.fn.imageLoader=function(i,m,h){this.each(function(){o(this,i,m,h)});return this});return o}(window,
document,window.Zepto,window.jQuery),Swapper=function(s,m,D,h){function v(d,a){var e=a.parentNode;e.lastchild===a?e.appendChild(d):e.insertBefore(d,a.nextSibling)}function o(d){d.parentNode&&d.parentNode.removeChild(d)}function y(d,a){d.style["-webkit-transform"]=a;d.style["-moz-transform"]=a;d.style["-ms-transform"]=a;d.style["-o-transform"]=a;d.style.transform=a}function z(d,a){a?(d.style["-webkit-transition"]="-webkit-"+a,d.style["-moz-transition"]="-moz-"+a,d.style["-ms-transition"]="-ms-"+a,
d.style["-o-transition"]="-o-"+a,d.style.transition=a):(d.style["-webkit-transition"]="",d.style["-moz-transition"]="",d.style["-ms-transition"]="",d.style["-o-transition"]="",d.style.transition="")}function i(d,a){var e;e=a?d.style:m.defaultView.getComputedStyle(d,null);return{display:e.display,opacity:e.opacity,top:e.top,left:e.left,height:e.height,width:e.width,position:e.position}}function I(d){var a;a:if(d){try{a=d instanceof Node||d instanceof HTMLElement;break a}catch(e){}a="object"!==typeof d||
"number"!==typeof d.nodeType||"string"!==typeof d.nodeName?!1:!0}else a=!1;if(!a)throw TypeError("element must be a DOM node, got "+d);}function k(d,a,e,h){function u(){F||(F=!0,a.removeEventListener("webkitTransitionEnd",u),a.removeEventListener("transitionend",u),a.removeEventListener("oTransitionEnd",u),a.removeEventListener("otransitionend",u),a.removeEventListener("MSTransitionEnd",u),a.removeEventListener("transitionend",u),o(d),z(d,""),z(a,""),setTimeout(function(){y(d,"");y(a,"");k[0].fade&&
(a.style.opacity=q.opacity);k[1].fade&&(d.style.opacity=E.opacity);a.style.position=q.position;a.style.top=q.top;a.style.left=q.left;a.style.height=q.height;a.style.width=q.width;d._swapper=!1;a._swapper=!1;h()},0))}I(d);I(a);"function"===typeof e&&(h=e,e={});switch(typeof e){case "string":e={transition:e};break;case "undefined":e={};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+e);}switch(typeof e.transition){case "string":if(!(e.transition in g)&&
"instant"!==e.transition)throw TypeError(e.transition+" is not a valid transition");break;case "undefined":break;default:throw TypeError("transition must be a string if defined, got "+e.transition);}switch(typeof e.duration){case "number":if(0>e.duration)throw TypeError("duration must be a non-negative integer, got "+e.duration);break;case "undefined":break;default:throw TypeError("duration must be a number if defined, got "+e.duration);}switch(typeof e.easing){case "string":if(!(e.easing in L))throw TypeError(e.easing+
" is not a valid easing");break;case "undefined":break;default:throw TypeError("easing must be a string if defined, got "+e.easing);}var A=h;switch(typeof A){case "undefined":A=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+A);}h=A;if(d._swapper)throw Error("elem1 is currently being swapped");if(a._swapper)throw Error("elem2 is currently being swapped");a:{for(A=d;A=A.parentNode;)if(A===m){A=!0;break a}A=!1}if(!A)throw Error("elem1 must be in the DOM to be swapped");
d._swapper=!0;a._swapper=!0;o(a);if("instant"===e.transition)v(a,d),o(d),d._swapper=!1,a._swapper=!1,setTimeout(function(){h()},0);else{var k=g[e.transition||"fade"],w=L[e.easing||"ease-in-out"],s=e.duration||300;v(a,d);var e=d.getBoundingClientRect(),A=i(d),j=i(a),E=i(d,!0),q=i(a,!0);"none"!==A.display&&(a.style.position="fixed",a.style.top=e.top+"px",a.style.left=e.left+"px");a.style.height=j.height||A.height;a.style.width=j.width||A.width;k[2]&&d.parentNode.insertBefore(a,d);y(d,t);y(a,k[0].transform||
t);k[0].fade&&(a.style.opacity="0");k[1].fade&&(d.style.opacity="1");setTimeout(function(){var e="transform "+s/1E3+"s "+w+", opacity "+s/1E3+"s "+w;z(d,e);z(a,e);setTimeout(function(){y(d,k[1].transform||t);y(a,t);k[0].fade&&(a.style.opacity="1");k[1].fade&&(d.style.opacity="0");a.addEventListener("webkitTransitionEnd",u,!1);a.addEventListener("transitionend",u,!1);a.addEventListener("oTransitionEnd",u,!1);a.addEventListener("otransitionend",u,!1);a.addEventListener("MSTransitionEnd",u,!1);a.addEventListener("transitionend",
u,!1);setTimeout(u,s+(K?300:0))},0)},0);var F=!1}}var t="translate3d(0,0,0) scale(1)",K=/\bandroid\b/i.test(navigator.userAgent),g={fade:[{fade:!0},{fade:!0}],"fade-on":[{fade:!0},{}],"fade-off":[{},{fade:!0},!0],"scale-in":[{transform:"scale(0.01)"},{}],"scale-out":[{},{transform:"scale(0.01)"},!0],"rotate-left":[{transform:"rotateY(-180deg) perspective(360px)",fade:!0},{transform:"rotateY( 180deg) perspective(360px)",fade:!0}],"rotate-right":[{transform:"rotateY( 180deg) perspective(360px)",fade:!0},
{transform:"rotateY(-180deg) perspective(360px)",fade:!0}],"cube-left":[{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"}],"cube-right":[{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"}],"swap-left":[{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"}],
"swap-right":[{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"}],"explode-in":[{fade:!0,transform:"scale(1.25)"},{}],"explode-out":[{},{fade:!0,transform:"scale(1.25)"},!0],"implode-in":[{},{fade:!0,transform:"scale(0.60)"},!0],"implode-out":[{fade:!0,transform:"scale(0.80)"},{}],"slide-left":[{transform:"translate3d( 100%,0,0)"},{transform:"translate3d(-100%,0,0)"}],"slide-right":[{transform:"translate3d(-100%,0,0)"},
{transform:"translate3d( 100%,0,0)"}],"slide-up":[{transform:"translate3d(0, 100%,0)"},{transform:"translate3d(0,-100%,0)"}],"slide-down":[{transform:"translate3d(0,-100%,0)"},{transform:"translate3d(0, 100%,0)"}],"slideon-left":[{transform:"translate3d(-100%,0,0)"},{}],"slideoff-left":[{},{transform:"translate3d(-100%,0,0)"},!0],"slideon-right":[{transform:"translate3d(100%,0,0)"},{}],"slideoff-right":[{},{transform:"translate3d(100%,0,0)"},!0],"slideon-up":[{transform:"translate3d(0,-100%,0)"},
{}],"slideoff-up":[{},{transform:"translate3d(0,-100%,0)"},!0],"slideon-down":[{transform:"translate3d(0,100%,0)"},{}],"slideoff-down":[{},{transform:"translate3d(0,100%,0)"},!0]},L={linear:"linear",ease:"ease","ease-in":"ease-in","ease-out":"ease-out","ease-in-out":"ease-in-out","step-start":"step-start","step-end":"step-end"};D&&D.extend(D.fn,{swapper:function(d,a,e){d=D(d)[0];this.forEach(function(g){k(g,d,a,e)});return this}});h&&(h.fn.swapper=function(d,a,e){d=h(d)[0];this.each(function(){k(this,
d,a,e)});return this});return k}(window,document,window.Zepto,window.jQuery),Clickable=function(s,m,D,h,v){function o(g,h){function d(){g.addEventListener("touchstart",w,!1);g.addEventListener("touchmove",v,!1);g.addEventListener("touchend",j,!1);g.addEventListener("touchcancel",v,!1)}function a(){g.removeEventListener("touchstart",w);g.removeEventListener("touchmove",v);g.removeEventListener("touchend",j);g.removeEventListener("touchcancel",v)}function e(){var d=g,a;a=g.className.replace(G,"");a=
String(a).replace(y,"");d.className=a}function k(a,d){do{if(a===d)return!0;if(a._clickable)break}while(a=a.parentNode);return!1}function u(a){C=!1;g.disabled||!k(a.target,g)?(a.preventDefault(),r=!1):(r=!0,g.className+=" "+h)}function o(a){a.preventDefault();C=r=!1;e()}function t(a){g.disabled?(a.preventDefault(),C=r=!1):(r?C=!0:(a.preventDefault(),C=!1),r=!1,e())}function w(a){C=!1;if(g.disabled||!k(a.target,g))r=!1;else{r=!0;var d=D=+new Date;setTimeout(function(){r&&d===D&&(g.className+=" "+h)},
z)}}function v(){r=C=!1;g.disabled||e()}function j(a){function d(){C=!0;var a=m.createEvent("MouseEvents");a.initMouseEvent("click",!0,!0,s,1,0,0,0,0,!1,!1,!1,!1,0,null);g.dispatchEvent(a)}var i=r;v();i&&!g.disabled&&(a.stopImmediatePropagation?+new Date-D>z?d():(g.className+=" "+h,setTimeout(function(){e();d()},1)):C=!0)}function E(a){a=a||s.event;if(!g.disabled&&C)C=!1;else return a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault(),a.stopPropagation(),a.cancelBubble=!0,a.returnValue=
!1}var q;a:if(g){try{q=g instanceof Node||g instanceof HTMLElement;break a}catch(F){}q="object"!==typeof g||"number"!==typeof g.nodeType||"string"!==typeof g.nodeName?!1:!0}else q=!1;if(!q)throw TypeError("element "+g+" must be a DOM element");if(!g._clickable){g._clickable=!0;switch(typeof h){case "undefined":h="active";case "string":break;default:throw TypeError("active class "+h+" must be a string");}g.setAttribute("data-clickable-class",h);var G=RegExp("\\b"+h+"\\b"),r=!1,C=!1,D;if(i.ios||i.android)if(g.style["-webkit-tap-highlight-color"]=
"rgba(255,255,255,0)",g.addEventListener("click",E,!1),i.ios){g.addEventListener("DOMNodeInsertedIntoDocument",d,!1);g.addEventListener("DOMNodeRemovedFromDocument",a,!1);a:{for(q=g;q=q.parentNode;)if(q===m){q=!0;break a}q=!1}q&&d()}else d();else g.addEventListener?(g.addEventListener("mousedown",u,!1),g.addEventListener("mousemove",o,!1),g.addEventListener("mouseout",o,!1),g.addEventListener("mouseup",t,!1),g.addEventListener("click",E,!1)):g.attachEvent&&(g.attachEvent("onmousedown",u),g.attachEvent("onmousemove",
o),g.attachEvent("onmouseout",o),g.attachEvent("onmouseup",t),g.attachEvent("onclick",E))}}var y=/^\s+|\s+$/g,z=40,i,I=s.navigator.userAgent,k,t,K;if(K=/\bCPU.*OS (\d+(_\d+)?)/i.exec(I))k="ios",t=K[1].replace("_",".");else if(K=/\bAndroid (\d+(\.\d+)?)/.exec(I))k="android",t=K[1];I={name:k,version:t&&s.parseFloat(t)};I[k]=!0;i=I;k=function(){o.apply(this,arguments)};D&&D.plugin("clickable",function(){o.apply(this,arguments)});h&&h.extend(h.fn,{clickable:function(g){this.forEach(function(h){o(h,g)});
return this}});v&&(v.fn.clickable=function(g){this.each(function(){o(this,g)});return this});k.touchable=function(){return i.ios||i.android};return k}(window,document,window.clik,window.Zepto,window.jQuery),Scrollable=function(s,m,D,h,v){function o(c){if(!c)return!1;try{return c instanceof Node||c instanceof HTMLElement}catch(b){}return"object"!==typeof c||"number"!==typeof c.nodeType||"string"!==typeof c.nodeName?!1:!0}function y(c,b,f){if(Array.prototype.forEach)Array.prototype.forEach.call(c,b,
f);else for(var a=0,d=c.length;a<d;a++)a in c&&b.call(f,c[a],a,c)}function z(c){g?setTimeout(c,0):K.push(c)}function i(c){try{m.documentElement.doScroll("left")}catch(b){setTimeout(function(){i(c)},1);return}c()}function I(c,b){function f(){var b=c._scrollTop(),f=c._scrollLeft();b===g&&f===p||(g=b,p=f,c.dispatchEvent&&(b=m.createEvent("MouseEvents"),b.initMouseEvent("scroll",!1,!1,s,0,0,0,0,0,!1,!1,!1,!1,0,null),c.dispatchEvent(b)))}if(!o(c))throw c+" is not a DOM element";if(!c._scrollable){c._scrollable=
!0;c.style.overflow="scroll";c._scrollTop=function(b){if("undefined"===typeof b)return e?Math.max(parseInt(-e.y),0):c.scrollTop;!e&&(!A||L)?c.scrollTop=b:z(function(){e.scrollTo(e.x,Math.min(-b,0),1)})};c._scrollLeft=function(b){if("undefined"===typeof b)return e?Math.max(parseInt(-e.x),0):c.scrollLeft;!e&&(!A||L)?c.scrollLeft=b:z(function(){e.scrollTo(Math.min(-b,0),e.y,1)})};if(!b){if(!A)return;if(L){c.style["-webkit-overflow-scrolling"]="touch";return}}var a=m.createElement("div"),n=Array.prototype.slice.call(c.childNodes||
[]);y(n,function(b){b=c.removeChild(b);a.appendChild(b)});c.appendChild(a);var e,g,p;c._iScroll=!0;z(function(){e=new aa(c,{checkDOMChanges:!0,useTransform:!0,useTransition:!0,hScrollbar:!1,vScrollbar:!1,bounce:!!d.ios,onScrollMove:f,onBeforeScrollEnd:f,onScrollEnd:f,onBeforeScrollStart:k})})}}function k(c){for(var b=c.target;1!==b.nodeType;)b=b.parentNode;"SELECT"!==b.tagName&&"INPUT"!==b.tagName&&"TEXTAREA"!==b.tagName&&c.preventDefault()}function t(c){return o(c)&&c._iScroll?c.childNodes[0]:c}
var K=[],g=!1,L=!1,d,a=navigator.userAgent,e,l,u;if(u=/\bCPU.*OS (\d+(_\d+)?)/i.exec(a))e="ios",l=u[1].replace("_",".");else if(u=/\bAndroid (\d+(\.\d+)?)/.exec(a))e="android",l=u[1];a={name:e,version:l&&s.parseFloat(l)};a[e]=!0;d=a;var A=!!d.name,aa;if(d.ios&&5<=d.version||d.android&&4<=d.version)L=!0;var w=s,T=m;e=function(c){if(""===E)return c;c=c.charAt(0).toUpperCase()+c.substr(1);return E+c};var j=Math,a=T.createElement("div").style,E;a:{l=["t","webkitT","MozT","msT","OT"];var q;u=0;for(var F=
l.length;u<F;u++)if(q=l[u]+"ransform",q in a){E=l[u].substr(0,l[u].length-1);break a}E=!1}var G=E?"-"+E.toLowerCase()+"-":"",r=e("transform"),C=e("transitionProperty"),M=e("transitionDuration"),O=e("transformOrigin"),P=e("transitionTimingFunction"),Q=e("transitionDelay"),N=/android/gi.test(navigator.appVersion),U=/iphone|ipad/gi.test(navigator.appVersion);l=/hp-tablet/gi.test(navigator.appVersion);var R=e("perspective")in a,x="ontouchstart"in w&&!l,n=!!E,p=e("transition")in a,ba="onorientationchange"in
w?"orientationchange":"resize",V=x?"touchstart":"mousedown",Y=x?"touchmove":"mousemove",B=x?"touchend":"mouseup",H=x?"touchcancel":"mouseup",W="Moz"==E?"DOMMouseScroll":"mousewheel",J;J=!1===E?!1:{"":"transitionend",webkit:"webkitTransitionEnd",Moz:"transitionend",O:"oTransitionEnd",ms:"MSTransitionEnd"}[E];var ga=w.requestAnimationFrame||w.webkitRequestAnimationFrame||w.mozRequestAnimationFrame||w.oRequestAnimationFrame||w.msRequestAnimationFrame||function(c){return setTimeout(c,1)},da=w.cancelRequestAnimationFrame||
w.webkitCancelAnimationFrame||w.webkitCancelRequestAnimationFrame||w.mozCancelRequestAnimationFrame||w.oCancelRequestAnimationFrame||w.msCancelRequestAnimationFrame||clearTimeout,S=R?" translateZ(0)":"";l=function(c,b){var f=this,a;f.wrapper="object"==typeof c?c:T.getElementById(c);f.wrapper.style.overflow="hidden";f.scroller=f.wrapper.children[0];f.options={hScroll:!0,vScroll:!0,x:0,y:0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,topOffset:0,checkDOMChanges:!1,
handleClick:!0,hScrollbar:!0,vScrollbar:!0,fixedScrollbar:N,hideScrollbar:U,fadeScrollbar:U&&R,scrollbarClass:"",zoom:!1,zoomMin:1,zoomMax:4,doubleTapZoom:2,wheelAction:"scroll",snap:!1,snapThreshold:1,onRefresh:null,onBeforeScrollStart:function(b){b.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null,onZoomStart:null,onZoom:null,onZoomEnd:null};for(a in b)f.options[a]=b[a];f.x=f.options.x;f.y=f.options.y;
f.options.useTransform=n&&f.options.useTransform;f.options.hScrollbar=f.options.hScroll&&f.options.hScrollbar;f.options.vScrollbar=f.options.vScroll&&f.options.vScrollbar;f.options.zoom=f.options.useTransform&&f.options.zoom;f.options.useTransition=p&&f.options.useTransition;f.options.zoom&&N&&(S="");f.scroller.style[C]=f.options.useTransform?G+"transform":"top left";f.scroller.style[M]="0";f.scroller.style[O]="0 0";f.options.useTransition&&(f.scroller.style[P]="cubic-bezier(0.33,0.66,0.66,1)");f.options.useTransform?
f.scroller.style[r]="translate("+f.x+"px,"+f.y+"px)"+S:f.scroller.style.cssText+=";position:absolute;top:"+f.y+"px;left:"+f.x+"px";f.options.useTransition&&(f.options.fixedScrollbar=!0);f.refresh();f._bind(ba,w);f._bind(V);x||(f._bind("mouseout",f.wrapper),"none"!=f.options.wheelAction&&f._bind(W));f.options.checkDOMChanges&&(f.checkDOMTime=setInterval(function(){f._checkDOMChanges()},500))};l.prototype={enabled:!0,x:0,y:0,steps:[],scale:1,currPageX:0,currPageY:0,pagesX:[],pagesY:[],aniTime:null,
wheelZoomCount:0,handleEvent:function(c){switch(c.type){case V:if(!x&&0!==c.button)break;this._start(c);break;case Y:this._move(c);break;case B:case H:this._end(c);break;case ba:this._resize();break;case W:this._wheel(c);break;case "mouseout":this._mouseout(c);break;case J:this._transitionEnd(c)}},_checkDOMChanges:function(){!this.moved&&!this.zoomed&&!(this.animating||this.scrollerW==this.scroller.offsetWidth*this.scale&&this.scrollerH==this.scroller.offsetHeight*this.scale)&&this.refresh()},_scrollbar:function(c){var b;
this[c+"Scrollbar"]?(this[c+"ScrollbarWrapper"]||(b=T.createElement("div"),this.options.scrollbarClass?b.className=this.options.scrollbarClass+c.toUpperCase():b.style.cssText="position:absolute;z-index:100;"+("h"==c?"height:7px;bottom:1px;left:2px;right:"+(this.vScrollbar?"7":"2")+"px":"width:7px;bottom:"+(this.hScrollbar?"7":"2")+"px;top:2px;right:1px"),b.style.cssText+=";pointer-events:none;"+G+"transition-property:opacity;"+G+"transition-duration:"+(this.options.fadeScrollbar?"350ms":"0")+";overflow:hidden;opacity:"+
(this.options.hideScrollbar?"0":"1"),this.wrapper.appendChild(b),this[c+"ScrollbarWrapper"]=b,b=T.createElement("div"),this.options.scrollbarClass||(b.style.cssText="position:absolute;z-index:100;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.9);"+G+"background-clip:padding-box;"+G+"box-sizing:border-box;"+("h"==c?"height:100%":"width:100%")+";"+G+"border-radius:3px;border-radius:3px"),b.style.cssText+=";pointer-events:none;"+G+"transition-property:"+G+"transform;"+G+"transition-timing-function:cubic-bezier(0.33,0.66,0.66,1);"+
G+"transition-duration:0;"+G+"transform: translate(0,0)"+S,this.options.useTransition&&(b.style.cssText+=";"+G+"transition-timing-function:cubic-bezier(0.33,0.66,0.66,1)"),this[c+"ScrollbarWrapper"].appendChild(b),this[c+"ScrollbarIndicator"]=b),"h"==c?(this.hScrollbarSize=this.hScrollbarWrapper.clientWidth,this.hScrollbarIndicatorSize=j.max(j.round(this.hScrollbarSize*this.hScrollbarSize/this.scrollerW),8),this.hScrollbarIndicator.style.width=this.hScrollbarIndicatorSize+"px",this.hScrollbarMaxScroll=
this.hScrollbarSize-this.hScrollbarIndicatorSize,this.hScrollbarProp=this.hScrollbarMaxScroll/this.maxScrollX):(this.vScrollbarSize=this.vScrollbarWrapper.clientHeight,this.vScrollbarIndicatorSize=j.max(j.round(this.vScrollbarSize*this.vScrollbarSize/this.scrollerH),8),this.vScrollbarIndicator.style.height=this.vScrollbarIndicatorSize+"px",this.vScrollbarMaxScroll=this.vScrollbarSize-this.vScrollbarIndicatorSize,this.vScrollbarProp=this.vScrollbarMaxScroll/this.maxScrollY),this._scrollbarPos(c,!0)):
this[c+"ScrollbarWrapper"]&&(n&&(this[c+"ScrollbarIndicator"].style[r]=""),this[c+"ScrollbarWrapper"].parentNode.removeChild(this[c+"ScrollbarWrapper"]),this[c+"ScrollbarWrapper"]=null,this[c+"ScrollbarIndicator"]=null)},_resize:function(){var c=this;setTimeout(function(){c.refresh()},N?200:0)},_pos:function(c,b){this.zoomed||(c=this.hScroll?c:0,b=this.vScroll?b:0,this.options.useTransform?this.scroller.style[r]="translate("+c+"px,"+b+"px) scale("+this.scale+")"+S:(c=j.round(c),b=j.round(b),this.scroller.style.left=
c+"px",this.scroller.style.top=b+"px"),this.x=c,this.y=b,this._scrollbarPos("h"),this._scrollbarPos("v"))},_scrollbarPos:function(c,b){var f="h"==c?this.x:this.y;this[c+"Scrollbar"]&&(f*=this[c+"ScrollbarProp"],0>f?(this.options.fixedScrollbar||(f=this[c+"ScrollbarIndicatorSize"]+j.round(3*f),8>f&&(f=8),this[c+"ScrollbarIndicator"].style["h"==c?"width":"height"]=f+"px"),f=0):f>this[c+"ScrollbarMaxScroll"]&&(this.options.fixedScrollbar?f=this[c+"ScrollbarMaxScroll"]:(f=this[c+"ScrollbarIndicatorSize"]-
j.round(3*(f-this[c+"ScrollbarMaxScroll"])),8>f&&(f=8),this[c+"ScrollbarIndicator"].style["h"==c?"width":"height"]=f+"px",f=this[c+"ScrollbarMaxScroll"]+(this[c+"ScrollbarIndicatorSize"]-f))),this[c+"ScrollbarWrapper"].style[Q]="0",this[c+"ScrollbarWrapper"].style.opacity=b&&this.options.hideScrollbar?"0":"1",this[c+"ScrollbarIndicator"].style[r]="translate("+("h"==c?f+"px,0)":"0,"+f+"px)")+S)},_start:function(c){var b=x?c.touches[0]:c,f,a;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,
c);(this.options.useTransition||this.options.zoom)&&this._transitionTime(0);this.zoomed=this.animating=this.moved=!1;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;this.options.zoom&&x&&1<c.touches.length&&(a=j.abs(c.touches[0].pageX-c.touches[1].pageX),f=j.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDistStart=j.sqrt(a*a+f*f),this.originX=j.abs(c.touches[0].pageX+c.touches[1].pageX-2*this.wrapperOffsetLeft)/2-this.x,this.originY=j.abs(c.touches[0].pageY+c.touches[1].pageY-
2*this.wrapperOffsetTop)/2-this.y,this.options.onZoomStart&&this.options.onZoomStart.call(this,c));if(this.options.momentum&&(this.options.useTransform?(f=getComputedStyle(this.scroller,null)[r].replace(/[^0-9\-.,]/g,"").split(","),a=1*f[4],f=1*f[5]):(a=1*getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,""),f=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),a!=this.x||f!=this.y))this.options.useTransition?this._unbind(J):da(this.aniTime),this.steps=[],this._pos(a,f);
this.absStartX=this.x;this.absStartY=this.y;this.startX=this.x;this.startY=this.y;this.pointX=b.pageX;this.pointY=b.pageY;this.startTime=c.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,c);this._bind(Y);this._bind(B);this._bind(H)}},_move:function(c){var b=x?c.touches[0]:c,f=b.pageX-this.pointX,a=b.pageY-this.pointY,d=this.x+f,e=this.y+a,n=c.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,c);if(this.options.zoom&&
x&&1<c.touches.length)d=j.abs(c.touches[0].pageX-c.touches[1].pageX),e=j.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDist=j.sqrt(d*d+e*e),this.zoomed=!0,b=1/this.touchesDistStart*this.touchesDist*this.scale,b<this.options.zoomMin?b=0.5*this.options.zoomMin*Math.pow(2,b/this.options.zoomMin):b>this.options.zoomMax&&(b=2*this.options.zoomMax*Math.pow(0.5,this.options.zoomMax/b)),this.lastScale=b/this.scale,d=this.originX-this.originX*this.lastScale+this.x,e=this.originY-this.originY*this.lastScale+
this.y,this.scroller.style[r]="translate("+d+"px,"+e+"px) scale("+b+")"+S,this.options.onZoom&&this.options.onZoom.call(this,c);else{this.pointX=b.pageX;this.pointY=b.pageY;if(0<d||d<this.maxScrollX)d=this.options.bounce?this.x+f/2:0<=d||0<=this.maxScrollX?0:this.maxScrollX;if(e>this.minScrollY||e<this.maxScrollY)e=this.options.bounce?this.y+a/2:e>=this.minScrollY||0<=this.maxScrollY?this.minScrollY:this.maxScrollY;this.distX+=f;this.distY+=a;this.absDistX=j.abs(this.distX);this.absDistY=j.abs(this.distY);
6>this.absDistX&&6>this.absDistY||(this.options.lockDirection&&(this.absDistX>this.absDistY+5?(e=this.y,a=0):this.absDistY>this.absDistX+5&&(d=this.x,f=0)),this.moved=!0,this._pos(d,e),this.dirX=0<f?-1:0>f?1:0,this.dirY=0<a?-1:0>a?1:0,300<n-this.startTime&&(this.startTime=n,this.startX=this.x,this.startY=this.y),this.options.onScrollMove&&this.options.onScrollMove.call(this,c))}},_end:function(c){if(!(x&&0!==c.touches.length)){var b=this,f=x?c.changedTouches[0]:c,a,d,e={dist:0,time:0},n={dist:0,time:0},
g=(c.timeStamp||Date.now())-b.startTime,p=b.x,h=b.y;b._unbind(Y);b._unbind(B);b._unbind(H);b.options.onBeforeScrollEnd&&b.options.onBeforeScrollEnd.call(b,c);if(b.zoomed)p=b.scale*b.lastScale,p=Math.max(b.options.zoomMin,p),p=Math.min(b.options.zoomMax,p),b.lastScale=p/b.scale,b.scale=p,b.x=b.originX-b.originX*b.lastScale+b.x,b.y=b.originY-b.originY*b.lastScale+b.y,b.scroller.style[M]="200ms",b.scroller.style[r]="translate("+b.x+"px,"+b.y+"px) scale("+b.scale+")"+S,b.zoomed=!1,b.refresh(),b.options.onZoomEnd&&
b.options.onZoomEnd.call(b,c);else{if(b.moved){if(300>g&&b.options.momentum){e=p?b._momentum(p-b.startX,g,-b.x,b.scrollerW-b.wrapperW+b.x,b.options.bounce?b.wrapperW:0):e;n=h?b._momentum(h-b.startY,g,-b.y,0>b.maxScrollY?b.scrollerH-b.wrapperH+b.y-b.minScrollY:0,b.options.bounce?b.wrapperH:0):n;p=b.x+e.dist;h=b.y+n.dist;if(0<b.x&&0<p||b.x<b.maxScrollX&&p<b.maxScrollX)e={dist:0,time:0};if(b.y>b.minScrollY&&h>b.minScrollY||b.y<b.maxScrollY&&h<b.maxScrollY)n={dist:0,time:0}}e.dist||n.dist?(e=j.max(j.max(e.time,
n.time),10),b.options.snap&&(n=p-b.absStartX,g=h-b.absStartY,j.abs(n)<b.options.snapThreshold&&j.abs(g)<b.options.snapThreshold?b.scrollTo(b.absStartX,b.absStartY,200):(n=b._snap(p,h),p=n.x,h=n.y,e=j.max(n.time,e))),b.scrollTo(j.round(p),j.round(h),e)):b.options.snap?(n=p-b.absStartX,g=h-b.absStartY,j.abs(n)<b.options.snapThreshold&&j.abs(g)<b.options.snapThreshold?b.scrollTo(b.absStartX,b.absStartY,200):(n=b._snap(b.x,b.y),(n.x!=b.x||n.y!=b.y)&&b.scrollTo(n.x,n.y,n.time))):b._resetPos(200)}else x&&
(b.doubleTapTimer&&b.options.zoom?(clearTimeout(b.doubleTapTimer),b.doubleTapTimer=null,b.options.onZoomStart&&b.options.onZoomStart.call(b,c),b.zoom(b.pointX,b.pointY,1==b.scale?b.options.doubleTapZoom:1),b.options.onZoomEnd&&setTimeout(function(){b.options.onZoomEnd.call(b,c)},200)):this.options.handleClick&&(b.doubleTapTimer=setTimeout(function(){b.doubleTapTimer=null;for(a=f.target;1!=a.nodeType;)a=a.parentNode;"SELECT"!=a.tagName&&"INPUT"!=a.tagName&&"TEXTAREA"!=a.tagName&&(d=T.createEvent("MouseEvents"),
d.initMouseEvent("click",!0,!0,c.view,1,f.screenX,f.screenY,f.clientX,f.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null),d._fake=!0,a.dispatchEvent(d))},b.options.zoom?250:0))),b._resetPos(200);b.options.onTouchEnd&&b.options.onTouchEnd.call(b,c)}}},_resetPos:function(c){var b=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,f=this.y>=this.minScrollY||0<this.maxScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:this.y;if(b==this.x&&f==this.y){if(this.moved&&(this.moved=
!1,this.options.onScrollEnd&&this.options.onScrollEnd.call(this)),this.hScrollbar&&this.options.hideScrollbar&&("webkit"==E&&(this.hScrollbarWrapper.style[Q]="300ms"),this.hScrollbarWrapper.style.opacity="0"),this.vScrollbar&&this.options.hideScrollbar)"webkit"==E&&(this.vScrollbarWrapper.style[Q]="300ms"),this.vScrollbarWrapper.style.opacity="0"}else this.scrollTo(b,f,c||0)},_wheel:function(c){var b=this,f,a;if("wheelDeltaX"in c)f=c.wheelDeltaX/12,a=c.wheelDeltaY/12;else if("wheelDelta"in c)f=a=
c.wheelDelta/12;else if("detail"in c)f=a=3*-c.detail;else return;if("zoom"==b.options.wheelAction){if(a=b.scale*Math.pow(2,1/3*(a?a/Math.abs(a):0)),a<b.options.zoomMin&&(a=b.options.zoomMin),a>b.options.zoomMax&&(a=b.options.zoomMax),a!=b.scale)!b.wheelZoomCount&&b.options.onZoomStart&&b.options.onZoomStart.call(b,c),b.wheelZoomCount++,b.zoom(c.pageX,c.pageY,a,400),setTimeout(function(){b.wheelZoomCount--;!b.wheelZoomCount&&b.options.onZoomEnd&&b.options.onZoomEnd.call(b,c)},400)}else f=b.x+f,a=b.y+
a,0<f?f=0:f<b.maxScrollX&&(f=b.maxScrollX),a>b.minScrollY?a=b.minScrollY:a<b.maxScrollY&&(a=b.maxScrollY),0>b.maxScrollY&&b.scrollTo(f,a,0)},_mouseout:function(c){var b=c.relatedTarget;if(b)for(;b=b.parentNode;)if(b==this.wrapper)return;this._end(c)},_transitionEnd:function(c){c.target==this.scroller&&(this._unbind(J),this._startAni())},_startAni:function(){var c=this,b=c.x,f=c.y,a=Date.now(),d,e,n;c.animating||(c.steps.length?(d=c.steps.shift(),d.x==b&&d.y==f&&(d.time=0),c.animating=!0,c.moved=!0,
c.options.useTransition)?(c._transitionTime(d.time),c._pos(d.x,d.y),c.animating=!1,d.time?c._bind(J):c._resetPos(0)):(n=function(){var p=Date.now(),g;p>=a+d.time?(c._pos(d.x,d.y),c.animating=!1,c.options.onAnimationEnd&&c.options.onAnimationEnd.call(c),c._startAni()):(p=(p-a)/d.time-1,e=j.sqrt(1-p*p),p=(d.x-b)*e+b,g=(d.y-f)*e+f,c._pos(p,g),c.animating&&(c.aniTime=ga(n)))},n()):c._resetPos(400))},_transitionTime:function(c){c+="ms";this.scroller.style[M]=c;this.hScrollbar&&(this.hScrollbarIndicator.style[M]=
c);this.vScrollbar&&(this.vScrollbarIndicator.style[M]=c)},_momentum:function(c,b,f,a,d){var b=j.abs(c)/b,e=b*b/0.0012;0<c&&e>f?(f+=d/(6/(6E-4*(e/b))),b=b*f/e,e=f):0>c&&e>a&&(a+=d/(6/(6E-4*(e/b))),b=b*a/e,e=a);return{dist:e*(0>c?-1:1),time:j.round(b/6E-4)}},_offset:function(c){for(var b=-c.offsetLeft,f=-c.offsetTop;c=c.offsetParent;)b-=c.offsetLeft,f-=c.offsetTop;c!=this.wrapper&&(b*=this.scale,f*=this.scale);return{left:b,top:f}},_snap:function(c,b){var f,a,d;d=this.pagesX.length-1;f=0;for(a=this.pagesX.length;f<
a;f++)if(c>=this.pagesX[f]){d=f;break}d==this.currPageX&&0<d&&0>this.dirX&&d--;c=this.pagesX[d];a=(a=j.abs(c-this.pagesX[this.currPageX]))?500*(j.abs(this.x-c)/a):0;this.currPageX=d;d=this.pagesY.length-1;for(f=0;f<d;f++)if(b>=this.pagesY[f]){d=f;break}d==this.currPageY&&0<d&&0>this.dirY&&d--;b=this.pagesY[d];f=(f=j.abs(b-this.pagesY[this.currPageY]))?500*(j.abs(this.y-b)/f):0;this.currPageY=d;d=j.round(j.max(a,f))||200;return{x:c,y:b,time:d}},_bind:function(c,b,a){(b||this.scroller).addEventListener(c,
this,!!a)},_unbind:function(c,b,a){(b||this.scroller).removeEventListener(c,this,!!a)},destroy:function(){this.scroller.style[r]="";this.vScrollbar=this.hScrollbar=!1;this._scrollbar("h");this._scrollbar("v");this._unbind(ba,w);this._unbind(V);this._unbind(Y);this._unbind(B);this._unbind(H);this.options.hasTouch||(this._unbind("mouseout",this.wrapper),this._unbind(W));this.options.useTransition&&this._unbind(J);this.options.checkDOMChanges&&clearInterval(this.checkDOMTime);this.options.onDestroy&&
this.options.onDestroy.call(this)},refresh:function(){var c,b,a,d=0;b=0;this.scale<this.options.zoomMin&&(this.scale=this.options.zoomMin);this.wrapperW=this.wrapper.clientWidth||1;this.wrapperH=this.wrapper.clientHeight||1;this.minScrollY=-this.options.topOffset||0;this.scrollerW=j.round(this.scroller.offsetWidth*this.scale);this.scrollerH=j.round((this.scroller.offsetHeight+this.minScrollY)*this.scale);this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH+this.minScrollY;
this.dirY=this.dirX=0;this.options.onRefresh&&this.options.onRefresh.call(this);this.hScroll=this.options.hScroll&&0>this.maxScrollX;this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);this.hScrollbar=this.hScroll&&this.options.hScrollbar;this.vScrollbar=this.vScroll&&this.options.vScrollbar&&this.scrollerH>this.wrapperH;c=this._offset(this.wrapper);this.wrapperOffsetLeft=-c.left;this.wrapperOffsetTop=-c.top;if("string"==typeof this.options.snap){this.pagesX=
[];this.pagesY=[];a=this.scroller.querySelectorAll(this.options.snap);c=0;for(b=a.length;c<b;c++)d=this._offset(a[c]),d.left+=this.wrapperOffsetLeft,d.top+=this.wrapperOffsetTop,this.pagesX[c]=d.left<this.maxScrollX?this.maxScrollX:d.left*this.scale,this.pagesY[c]=d.top<this.maxScrollY?this.maxScrollY:d.top*this.scale}else if(this.options.snap){for(this.pagesX=[];d>=this.maxScrollX;)this.pagesX[b]=d,d-=this.wrapperW,b++;this.maxScrollX%this.wrapperW&&(this.pagesX[this.pagesX.length]=this.maxScrollX-
this.pagesX[this.pagesX.length-1]+this.pagesX[this.pagesX.length-1]);b=d=0;for(this.pagesY=[];d>=this.maxScrollY;)this.pagesY[b]=d,d-=this.wrapperH,b++;this.maxScrollY%this.wrapperH&&(this.pagesY[this.pagesY.length]=this.maxScrollY-this.pagesY[this.pagesY.length-1]+this.pagesY[this.pagesY.length-1])}this._scrollbar("h");this._scrollbar("v");this.zoomed||(this.scroller.style[M]="0",this._resetPos(200))},scrollTo:function(c,b,a,d){var e=c;this.stop();e.length||(e=[{x:c,y:b,time:a,relative:d}]);c=0;
for(b=e.length;c<b;c++)e[c].relative&&(e[c].x=this.x-e[c].x,e[c].y=this.y-e[c].y),this.steps.push({x:e[c].x,y:e[c].y,time:e[c].time||0});this._startAni()},scrollToElement:function(c,b){var a;if(c=c.nodeType?c:this.scroller.querySelector(c))a=this._offset(c),a.left+=this.wrapperOffsetLeft,a.top+=this.wrapperOffsetTop,a.left=0<a.left?0:a.left<this.maxScrollX?this.maxScrollX:a.left,a.top=a.top>this.minScrollY?this.minScrollY:a.top<this.maxScrollY?this.maxScrollY:a.top,b=void 0===b?j.max(2*j.abs(a.left),
2*j.abs(a.top)):b,this.scrollTo(a.left,a.top,b)},scrollToPage:function(c,b,a){a=void 0===a?400:a;this.options.onScrollStart&&this.options.onScrollStart.call(this);if(this.options.snap)c="next"==c?this.currPageX+1:"prev"==c?this.currPageX-1:c,b="next"==b?this.currPageY+1:"prev"==b?this.currPageY-1:b,c=0>c?0:c>this.pagesX.length-1?this.pagesX.length-1:c,b=0>b?0:b>this.pagesY.length-1?this.pagesY.length-1:b,this.currPageX=c,this.currPageY=b,c=this.pagesX[c],b=this.pagesY[b];else if(c*=-this.wrapperW,
b*=-this.wrapperH,c<this.maxScrollX&&(c=this.maxScrollX),b<this.maxScrollY)b=this.maxScrollY;this.scrollTo(c,b,a)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(Y);this._unbind(B);this._unbind(H)},enable:function(){this.enabled=!0},stop:function(){this.options.useTransition?this._unbind(J):da(this.aniTime);this.steps=[];this.animating=this.moved=!1},zoom:function(c,b,a,d){var e=a/this.scale;this.options.useTransform&&(this.zoomed=!0,d=void 0===d?200:d,c=c-this.wrapperOffsetLeft-
this.x,b=b-this.wrapperOffsetTop-this.y,this.x=c-c*e+this.x,this.y=b-b*e+this.y,this.scale=a,this.refresh(),this.x=0<this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,this.y=this.y>this.minScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:this.y,this.scroller.style[M]=d+"ms",this.scroller.style[r]="translate("+this.x+"px,"+this.y+"px) scale("+a+")"+S,this.zoomed=!1)},isReady:function(){return!this.moved&&!this.zoomed&&!this.animating}};a=null;aa=l;var X=function(){g||(g=!0,y(K,function(c){setTimeout(c,
0)}))};if("complete"===m.readyState)setTimeout(X,0);else if(m.addEventListener)m.addEventListener("DOMContentLoaded",X,!1),s.addEventListener("load",X,!1);else if(m.attachEvent){m.attachEvent("onreadystatechange",X);s.attachEvent("onload",X);q=!1;try{q=null===s.frameElement}catch(ha){}m.documentElement.doScroll&&q&&setTimeout(function(){i(X)},0)}q=function(){I.apply(this,arguments)};e=function(){I.apply(this,arguments)};D&&(e.node=function(){return t.apply(this,arguments)},D.plugin("scrollable",e));
if(h){h.extend(h.fn,{scrollable:function(c){this.forEach(function(b){I(b,c)});return this},scrollableNode:function(){return $(this.map(function(){return t(this)}))}});var Z=h.fn.scrollTop,ca=h.fn.scrollLeft;h.fn.scrollTop=function(c){if("undefined"===typeof c){var b=this[0],a=o(b);return a&&b._scrollTop?b._scrollTop():Z?Z.apply(this,arguments):a?b.scrollTop:null}this.forEach(function(b){var a=o(b);a&&b._scrollTop?b._scrollTop(c):Z?Z.call(h(b),c):a&&(b.scrollTop=c)});return this};h.fn.scrollLeft=function(c){if("undefined"===
typeof c){var b=this[0],a=o(b);return a&&b._scrollLeft?b._scrollLeft():Z?ca.apply(this,arguments):a?b.scrollLeft:null}this.forEach(function(b){var a=o(b);a&&b._scrollLeft?b._scrollLeft(c):ca?ca.call(h(b),c):a&&(b.scrollLeft=c)});return this}}if(v){v.fn.scrollable=function(c){this.each(function(){I(this,c)});return this};v.fn.scrollableNode=function(){return $(this.map(function(){return t(this)}))};var ea=v.fn.scrollTop,fa=v.fn.scrollLeft;v.fn.scrollTop=function(c){if("undefined"===typeof c){var b=
this[0];return o(b)&&b._scrollTop?b._scrollTop():ea.apply(this,arguments)}this.each(function(){o(this)&&this._scrollTop?this._scrollTop(c):ea.call(v(this),c)});return this};v.fn.scrollLeft=function(c){if("undefined"===typeof c){var b=this[0];return o(b)&&b._scrollLeft?b._scrollLeft():fa.apply(this,arguments)}this.each(function(){o(this)&&this._scrollLeft?this._scrollLeft(c):fa.call(v(this),c)});return this}}q.node=function(){return t.apply(this,arguments)};return q}(window,document,window.clik,window.Zepto,
window.jQuery);
(function(s,m,D,h,v,o,y,z){function i(a,d){d?a.setAttribute(l,d):d=a.getAttribute(l);"string"===typeof d&&0!==d.length&&(a.parentNode.removeChild(a),G[d]=a.cloneNode(!0))}function I(a,d){a.addEventListener("click",function(){function e(){g||(g=!0,a.disabled=!1,a.className=a.className.replace(RegExp("\\b"+h+"\\b","g"),""))}var g=!1,h=a.getAttribute("data-clickable-class")||"active",i;a.disabled=!0;a.className+=" "+h;try{i=d(e)}catch(j){e()}!1===i&&e()},!1)}function k(n,p,h,V){function l(){Array.prototype.forEach.call(J.querySelectorAll(".app-content"),function(a){a.getAttribute("data-no-scroll")||
o(a)});O=!1;setTimeout(K,0);V()}if(O){if(+new Date>O+w){M.push(["load",n,p,h,V]);return}return!1}O=+new Date;if(!R){for(var B=m.getElementsByClassName(e),H=B.length;H--;)i(B[H]);if(B=/\bCPU.*OS (\d+(_\d+)?)/i.exec(navigator.userAgent))P="ios",Q=parseFloat(B[1]),m.body.className+=" "+u,N=T,U=q[N];else if(B=/\bAndroid (\d+(\.\d+)?)/.exec(navigator.userAgent))P="android",Q=parseFloat(B[1]),m.body.className+=" "+A,N=4<=Q?j:E,U=q[N];F.platform=P;F.platformVersion=Q;m.body.className+=" "+aa}var W={},J;
if(!(n in G))throw TypeError(n+" is not a known page");var s=G[n].cloneNode(!0),B=r[n]||[];a(s);Array.prototype.forEach.call(s.querySelectorAll(".app-button"),function(a){v(a);var d=a.getAttribute("data-target");a.getAttribute("data-back")?I(a,function(a){return t({},a)}):d&&I(a,function(a){return k(d,{},{},a)})});B.forEach(function(a){a[0].call(W,s,p)});Array.prototype.forEach.call(s.querySelectorAll("img"),function(a){if(a.getAttribute("data-auto-load")){var d="android"===P?400:0,e=a.src;a.src=
"";D(a,e,d)}});J=s;if(R){B=x;if((H=d(B))&&!H._iScroll)H=H._scrollTop(),(B||x).setAttribute("data-last-scroll",H+"");B=x;if((H=d(B))&&!H._iScroll){var z=H.style["-webkit-overflow-scrolling"]||"";H.style["-webkit-overflow-scrolling"]="";(B||x).setAttribute("data-scroll-style",z)}var B={},y;for(y in h)B[y]=h[y];g(J,B,l)}else m.body.appendChild(J),setTimeout(l,0);R=n;x=J;C.push([n,J,h,p,W])}function t(e,p){if(O){if(+new Date>O+w){M.push(["back",e,p]);return}return!1}if(2>C.length)throw Error("navigation stack is empty");
O=+new Date;var h=C.pop(),i=C[C.length-1],j=i[0],m=i[1],i=h[2];a(m);Array.prototype.forEach.call(h[1].querySelectorAll("*"),function(a){a.style["-webkit-overflow-scrolling"]=""});var k=d(m);if(k&&!k._iScroll){var o=parseInt((m||x).getAttribute("data-last-scroll"));o&&k._scrollTop(o)}var k={},l;for(l in i)k[l]=i[l];for(l in e)k[l]=e[l];g(m,k,function(){var a=d(m);if(a&&!a._iScroll){var e=(m||x).getAttribute("data-scroll-style")||"";a.style["-webkit-overflow-scrolling"]=e}setTimeout(K,0);var a=h[0],
n=h[1],g=h[3],i=h[4];if(!(a in G))throw TypeError(a+" is not a known page");(r[a]||[]).forEach(function(a){a[1].call(i,n,g)});O=!1;p()},!0);R=j;x=m}function K(){if(0!==M.length){var a=M.shift();switch(a.shift()){case "load":k.apply(s,a);break;case "back":t.apply(s,a)}}}function g(a,d,e,g){function i(){m.body.removeChild(k);e()}function j(){--A||(c(),b(),f(),l.appendChild(o),a.appendChild(v),h(l,a,"instant"),i())}var k=m.createElement("div");k.className="app-clickblocker";m.body.appendChild(k);var l=
x;if(d.transition)g&&(d.transition=q[d.transition]||d.transition),h(l,a,d,i);else if(d.transition=g?U:N,"ios"!==P||"slide-left"!==d.transition&&"slide-right"!==d.transition)h(l,a,d,i);else{var g=l.querySelector(".app-topbar"),o=l.querySelector(".app-content"),s=l.querySelector(".app-topbar .app-title"),t=l.querySelector(".app-topbar .left.app-button"),u=l.querySelector(".app-topbar .right.app-button"),r=a.querySelector(".app-topbar"),v=a.querySelector(".app-content"),w=a.querySelector(".app-topbar .app-title"),
y=a.querySelector(".app-topbar .left.app-button"),z=a.querySelector(".app-topbar .right.app-button");if(!g||!r||!o||!v)h(l,a,d,i);else{var A=4,c=L(g,r,s,w,d,j),b=L(g,r,t,y,d,j),f=L(g,r,u,z,d,j);h(o,v,d,j)}}}function L(a,d,e,g,i,j){var l=function(){};if(e&&g)h(e,g,{easing:i.easing,duration:i.duration,transition:"fade"},j),l=function(){a.appendChild(e);d.appendChild(g)};else if(e){var k=m.createElement("div");k.className=e.className;k.innerHTML=e.innerHTML;k.style.visibility="hidden";h(e,k,{easing:i.easing,
duration:i.duration,transition:"fade"},j);l=function(){a.removeChild(k);a.appendChild(e)}}else g?(k=m.createElement("div"),k.className=g.className,k.innerHTML=g.innerHTML,k.style.visibility="hidden",a.appendChild(k),h(k,g,{easing:i.easing,duration:i.duration,transition:"fade"},j),l=function(){d.appendChild(g)}):setTimeout(j,0);return l}function d(a){if(a=a||x)if((a=a.querySelector(".app-content"))&&a._scrollable)return a}function a(a){var d=a.querySelector(".app-topbar");if(a=a.querySelector(".app-content")){var e=
s.innerHeight;if(d){var d=m.defaultView.getComputedStyle(d,null),g="android"===P?48:44;d.height&&(g=parseInt(d.height)||0);a.style.height=e-g+"px"}else a.style.height=e+"px"}}var e="app-page",l="data-page",u="app-ios",A="app-android",aa="app-loaded",w=300,T="slide-left",j="implode-out",E="fade-on",q={fade:"fade","fade-on":"fade-off","fade-off":"fade-on","scale-in":"scale-out","scale-out":"scale-in","rotate-left":"rotate-right","rotate-right":"rotate-left","cube-left":"cube-right","cube-right":"cube-left",
"swap-left":"swap-right","swap-right":"swap-left","explode-in":"explode-out","explode-out":"explode-in","implode-in":"implode-out","implode-out":"implode-in","slide-left":"slide-right","slide-right":"slide-left","slide-up":"slide-down","slide-down":"slide-up","slideon-left":"slideoff-left","slideon-right":"slideoff-right","slideon-up":"slideoff-up","slideon-down":"slideoff-down","slideoff-left":"slideon-left","slideoff-right":"slideon-right","slideoff-up":"slideon-up","slideoff-down":"slideon-down"},
F={},G={},r={},C=[],M=[],O=!1,P,Q,N,U,R,x;F.platform=null;F.platformVersion=null;F.current=function(){return R};F.add=function(a,d){"string"!==typeof a&&(d=a,a=void 0);var e;a:if(d){try{e=d instanceof Node||d instanceof HTMLElement;break a}catch(g){}e="object"!==typeof d||"number"!==typeof d.nodeType||"string"!==typeof d.nodeName?!1:!0}else e=!1;if(!e)throw TypeError("page template node must be a DOM node, got "+d);i(d,a)};F.populator=function(a,d,e){if("string"!==typeof a)throw TypeError("page name must be a string, got "+
a);if("function"!==typeof d)throw TypeError("page populator must be a function, got "+d);switch(typeof e){case "undefined":e=function(){};break;case "function":break;default:throw TypeError("page unpopulator must be a function, got "+e);}r[a]||(r[a]=[]);r[a].push([d,e])};F.load=function(a,d,e,g){if("string"!==typeof a)throw TypeError("page name must be a string, got "+a);switch(typeof d){case "function":g=d;d={};e={};break;case "undefined":d={};break;case "string":e=d;d={};break;case "object":break;
default:throw TypeError("page arguments must be an object if defined, got "+d);}switch(typeof e){case "function":g=e;e={};break;case "undefined":e={};break;case "string":e={transition:e};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+e);}switch(typeof g){case "undefined":g=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+g);}k(a,d,e,g)};F.back=function(a,d){switch(typeof a){case "function":d=
a;a={};break;case "undefined":a={};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+a);}switch(typeof d){case "undefined":d=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+d);}t(a,d)};F.setDefaultTransition=function(a){if(!(a in q))throw TypeError("invalid transition type, got "+a);N=a;U=q[N]};s.addEventListener("resize",function(){x&&a(x)});y&&y.browser.back&&y.browser.back(function(){if(1<
C.length)return F.back(),!1});z&&(z.plugin&&z.plugin.back)&&z.plugin.back(function(){if(1<C.length)return F.back(),!1});s.App=F})(window,document,ImageLoader,Swapper,Clickable,Scrollable,window.picard,window.clik);
