var ImageLoader=function(m,n,z,h){function s(i,o){i.style["-webkit-transition"]=o;i.style["-moz-transition"]=o;i.style["-ms-transition"]=o;i.style["-o-transition"]=o;i.style.transition=o}function p(i,o,h,p){function m(){e||(e=!0,E[o]=!0,i.src=o,i.style.opacity="1",setTimeout(function(){s(i,"");setTimeout(function(){i.style.opacity=d.opacity;i.style["-webkit-transition"]=d["-webkit-transition"];i.style["-moz-transition"]=d["-moz-transition"];i.style["-ms-transition"]=d["-ms-transition"];i.style["-o-transition"]=
d["-o-transition"];i.style.transition=d.transition;p()},0)},v),n.body.removeChild(k))}var g;a:if(i){try{g=i instanceof Node||i instanceof HTMLElement;break a}catch(H){}g="object"!==typeof i||"number"!==typeof i.nodeType||"string"!==typeof i.nodeName?!1:!0}else g=!1;if(!g)throw TypeError("image must be a DOM element, got "+i);if("string"!==typeof o)throw TypeError("url must be a string, got "+o);switch(typeof h){case "function":p=h;case "undefined":h=0;case "number":break;default:throw TypeError("minimum wait time must be a number if deinfed, got "+
h);}switch(typeof p){case "undefined":p=function(){};case "function":break;default:throw TypeError("callback must be a function if defined, got "+p);}if(!0===E[o])i.src=o;else{var e=!1,a=+new Date+(h||0),d={opacity:i.style.opacity,"-webkit-transition":i.style["-webkit-transition"],"-moz-transition":i.style["-moz-transition"],"-ms-transition":i.style["-ms-transition"],"-o-transition":i.style["-o-transition"],transition:i.style.transition};i.style.opacity="0";setTimeout(function(){s(i,"opacity "+v/
1E3+"s ease-in-out")},0);var k=new Image;k.style.opacity="0";k.style.position="fixed";k.style.top="-100%";k.style.left="-100%";k.style.height="1px";k.style.width="1px";n.body.appendChild(k);k.onload=function(){var e=+new Date;e>=a?m():setTimeout(m,a-e)};k.onerror=k.onload;k.src=o}}var v=300,E={};z&&z.extend(z.fn,{imageLoader:function(i,h,n){this.forEach(function(m){p(m,i,h,n)});return this}});h&&(h.fn.imageLoader=function(i,h,n){this.each(function(){p(this,i,h,n)});return this});return p}(window,
document,window.Zepto,window.jQuery),Swapper=function(m,n,z,h){function s(e,a){var d=a.parentNode;d.lastchild===a?d.appendChild(e):d.insertBefore(e,a.nextSibling)}function p(e){e.parentNode&&e.parentNode.removeChild(e)}function v(e,a){e.style["-webkit-transform"]=a;e.style["-moz-transform"]=a;e.style["-ms-transform"]=a;e.style["-o-transform"]=a;e.style.transform=a}function E(e,a){a?(e.style["-webkit-transition"]="-webkit-"+a,e.style["-moz-transition"]="-moz-"+a,e.style["-ms-transition"]="-ms-"+a,
e.style["-o-transition"]="-o-"+a,e.style.transition=a):(e.style["-webkit-transition"]="",e.style["-moz-transition"]="",e.style["-ms-transition"]="",e.style["-o-transition"]="",e.style.transition="")}function i(e,a){var d;d=a?e.style:n.defaultView.getComputedStyle(e,null);return{display:d.display,opacity:d.opacity,top:d.top,left:d.left,height:d.height,width:d.width,position:d.position}}function o(e){var a;a:if(e){try{a=e instanceof Node||e instanceof HTMLElement;break a}catch(d){}a="object"!==typeof e||
"number"!==typeof e.nodeType||"string"!==typeof e.nodeName?!1:!0}else a=!1;if(!a)throw TypeError("element must be a DOM node, got "+e);}function r(e,a,d,k){function h(){z||(z=!0,a.removeEventListener("webkitTransitionEnd",h),a.removeEventListener("transitionend",h),a.removeEventListener("oTransitionEnd",h),a.removeEventListener("otransitionend",h),a.removeEventListener("MSTransitionEnd",h),a.removeEventListener("transitionend",h),p(e),E(e,""),E(a,""),setTimeout(function(){v(e,"");v(a,"");m[0].fade&&
(a.style.opacity=l.opacity);m[1].fade&&(e.style.opacity=u.opacity);a.style.position=l.position;a.style.top=l.top;a.style.left=l.left;a.style.height=l.height;a.style.width=l.width;e._swapper=!1;a._swapper=!1;k()},0))}o(e);o(a);"function"===typeof d&&(k=d,d={});switch(typeof d){case "string":d={transition:d};break;case "undefined":d={};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+d);}switch(typeof d.transition){case "string":if(!(d.transition in g)&&
"instant"!==d.transition)throw TypeError(d.transition+" is not a valid transition");break;case "undefined":break;default:throw TypeError("transition must be a string if defined, got "+d.transition);}switch(typeof d.duration){case "number":if(0>d.duration)throw TypeError("duration must be a non-negative integer, got "+d.duration);break;case "undefined":break;default:throw TypeError("duration must be a number if defined, got "+d.duration);}switch(typeof d.easing){case "string":if(!(d.easing in H))throw TypeError(d.easing+
" is not a valid easing");break;case "undefined":break;default:throw TypeError("easing must be a string if defined, got "+d.easing);}var w=k;switch(typeof w){case "undefined":w=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+w);}k=w;if(e._swapper)throw Error("elem1 is currently being swapped");if(a._swapper)throw Error("elem2 is currently being swapped");a:{for(w=e;w=w.parentNode;)if(w===n){w=!0;break a}w=!1}if(!w)throw Error("elem1 must be in the DOM to be swapped");
e._swapper=!0;a._swapper=!0;p(a);if("instant"===d.transition)s(a,e),p(e),e._swapper=!1,a._swapper=!1,setTimeout(function(){k()},0);else{var m=g[d.transition||"fade"],t=H[d.easing||"ease-in-out"],r=d.duration||300;s(a,e);var d=e.getBoundingClientRect(),w=i(e),j=i(a),u=i(e,!0),l=i(a,!0);"none"!==w.display&&(a.style.position="fixed",a.style.top=d.top+"px",a.style.left=d.left+"px");a.style.height=j.height||w.height;a.style.width=j.width||w.width;m[2]&&e.parentNode.insertBefore(a,e);v(e,D);v(a,m[0].transform||
D);m[0].fade&&(a.style.opacity="0");m[1].fade&&(e.style.opacity="1");setTimeout(function(){var d="transform "+r/1E3+"s "+t+", opacity "+r/1E3+"s "+t;E(e,d);E(a,d);setTimeout(function(){v(e,m[1].transform||D);v(a,D);m[0].fade&&(a.style.opacity="1");m[1].fade&&(e.style.opacity="0");a.addEventListener("webkitTransitionEnd",h,!1);a.addEventListener("transitionend",h,!1);a.addEventListener("oTransitionEnd",h,!1);a.addEventListener("otransitionend",h,!1);a.addEventListener("MSTransitionEnd",h,!1);a.addEventListener("transitionend",
h,!1);setTimeout(h,r+(K?300:0))},0)},0);var z=!1}}var D="translate3d(0,0,0) scale(1)",K=/\bandroid\b/i.test(navigator.userAgent),g={fade:[{fade:!0},{fade:!0}],"fade-on":[{fade:!0},{}],"fade-off":[{},{fade:!0},!0],"scale-in":[{transform:"scale(0.01)"},{}],"scale-out":[{},{transform:"scale(0.01)"},!0],"rotate-left":[{transform:"rotateY(-180deg) perspective(360px)",fade:!0},{transform:"rotateY( 180deg) perspective(360px)",fade:!0}],"rotate-right":[{transform:"rotateY( 180deg) perspective(360px)",fade:!0},
{transform:"rotateY(-180deg) perspective(360px)",fade:!0}],"cube-left":[{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"}],"cube-right":[{transform:"translate3d(-50%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d( 50%,0,0) rotateY(-90deg) perspective(360px)"}],"swap-left":[{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"},{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"}],
"swap-right":[{transform:"translate3d(-65%,0,0) rotateY(-90deg) perspective(360px)"},{transform:"translate3d( 65%,0,0) rotateY( 90deg) perspective(360px)"}],"explode-in":[{fade:!0,transform:"scale(1.25)"},{}],"explode-out":[{},{fade:!0,transform:"scale(1.25)"},!0],"implode-in":[{},{fade:!0,transform:"scale(0.60)"},!0],"implode-out":[{fade:!0,transform:"scale(0.80)"},{}],"slide-left":[{transform:"translate3d( 100%,0,0)"},{transform:"translate3d(-100%,0,0)"}],"slide-right":[{transform:"translate3d(-100%,0,0)"},
{transform:"translate3d( 100%,0,0)"}],"slide-up":[{transform:"translate3d(0, 100%,0)"},{transform:"translate3d(0,-100%,0)"}],"slide-down":[{transform:"translate3d(0,-100%,0)"},{transform:"translate3d(0, 100%,0)"}],"slideon-left":[{transform:"translate3d(-100%,0,0)"},{}],"slideoff-left":[{},{transform:"translate3d(-100%,0,0)"},!0],"slideon-right":[{transform:"translate3d(100%,0,0)"},{}],"slideoff-right":[{},{transform:"translate3d(100%,0,0)"},!0],"slideon-up":[{transform:"translate3d(0,-100%,0)"},
{}],"slideoff-up":[{},{transform:"translate3d(0,-100%,0)"},!0],"slideon-down":[{transform:"translate3d(0,100%,0)"},{}],"slideoff-down":[{},{transform:"translate3d(0,100%,0)"},!0]},H={linear:"linear",ease:"ease","ease-in":"ease-in","ease-out":"ease-out","ease-in-out":"ease-in-out","step-start":"step-start","step-end":"step-end"};z&&z.extend(z.fn,{swapper:function(e,a,d){e=z(e)[0];this.forEach(function(g){r(g,e,a,d)});return this}});h&&(h.fn.swapper=function(e,a,d){e=h(e)[0];this.each(function(){r(this,
e,a,d)});return this});return r}(window,document,window.Zepto,window.jQuery),Clickable=function(m,n,z,h,s){function p(g,h){function e(){g.addEventListener("touchstart",t,!1);g.addEventListener("touchmove",s,!1);g.addEventListener("touchend",j,!1);g.addEventListener("touchcancel",s,!1)}function a(){g.removeEventListener("touchstart",t);g.removeEventListener("touchmove",s);g.removeEventListener("touchend",j);g.removeEventListener("touchcancel",s)}function d(){var e=g,a;a=g.className.replace(A,"");a=
String(a).replace(v,"");e.className=a}function k(a,e){do{if(a===e)return!0;if(a._clickable)break}while(a=a.parentNode);return!1}function p(a){C=!1;g.disabled||!k(a.target,g)?(a.preventDefault(),q=!1):(q=!0,g.className+=" "+h)}function o(a){a.preventDefault();C=q=!1;d()}function r(a){g.disabled?(a.preventDefault(),C=q=!1):(q?C=!0:(a.preventDefault(),C=!1),q=!1,d())}function t(a){C=!1;if(g.disabled||!k(a.target,g))q=!1;else{q=!0;var e=B=+new Date;setTimeout(function(){q&&e===B&&(g.className+=" "+h)},
E)}}function s(){q=C=!1;g.disabled||d()}function j(a){function e(){C=!0;var a=n.createEvent("MouseEvents");a.initMouseEvent("click",!0,!0,m,1,0,0,0,0,!1,!1,!1,!1,0,null);g.dispatchEvent(a)}var i=q;s();i&&!g.disabled&&(a.stopImmediatePropagation?+new Date-B>E?e():(g.className+=" "+h,setTimeout(function(){d();e()},1)):C=!0)}function u(a){a=a||m.event;if(!g.disabled&&C)C=!1;else return a.stopImmediatePropagation&&a.stopImmediatePropagation(),a.preventDefault(),a.stopPropagation(),a.cancelBubble=!0,a.returnValue=
!1}var l;a:if(g){try{l=g instanceof Node||g instanceof HTMLElement;break a}catch(z){}l="object"!==typeof g||"number"!==typeof g.nodeType||"string"!==typeof g.nodeName?!1:!0}else l=!1;if(!l)throw TypeError("element "+g+" must be a DOM element");if(!g._clickable){g._clickable=!0;switch(typeof h){case "undefined":h="active";case "string":break;default:throw TypeError("active class "+h+" must be a string");}g.setAttribute("data-clickable-class",h);var A=RegExp("\\b"+h+"\\b"),q=!1,C=!1,B;if(i.ios||i.android)if(g.style["-webkit-tap-highlight-color"]=
"rgba(255,255,255,0)",g.addEventListener("click",u,!1),i.ios){g.addEventListener("DOMNodeInsertedIntoDocument",e,!1);g.addEventListener("DOMNodeRemovedFromDocument",a,!1);a:{for(l=g;l=l.parentNode;)if(l===n){l=!0;break a}l=!1}l&&e()}else e();else g.addEventListener?(g.addEventListener("mousedown",p,!1),g.addEventListener("mousemove",o,!1),g.addEventListener("mouseout",o,!1),g.addEventListener("mouseup",r,!1),g.addEventListener("click",u,!1)):g.attachEvent&&(g.attachEvent("onmousedown",p),g.attachEvent("onmousemove",
o),g.attachEvent("onmouseout",o),g.attachEvent("onmouseup",r),g.attachEvent("onclick",u))}}var v=/^\s+|\s+$/g,E=40,i,o=m.navigator.userAgent,r,D,K;if(K=/\bCPU.*OS (\d+(_\d+)?)/i.exec(o))r="ios",D=K[1].replace("_",".");else if(K=/\bAndroid (\d+(\.\d+)?)/.exec(o))r="android",D=K[1];o={name:r,version:D&&m.parseFloat(D)};o[r]=!0;i=o;r=function(){p.apply(this,arguments)};z&&z.plugin("clickable",function(){p.apply(this,arguments)});h&&h.extend(h.fn,{clickable:function(g){this.forEach(function(h){p(h,g)});
return this}});s&&(s.fn.clickable=function(g){this.each(function(){p(this,g)});return this});r.touchable=function(){return i.ios||i.android};return r}(window,document,window.clik,window.Zepto,window.jQuery),Scrollable=function(m,n,z,h,s){function p(c){if(!c)return!1;try{return c instanceof Node||c instanceof HTMLElement}catch(b){}return"object"!==typeof c||"number"!==typeof c.nodeType||"string"!==typeof c.nodeName?!1:!0}function v(c,b,f){if(Array.prototype.forEach)Array.prototype.forEach.call(c,b,
f);else for(var a=0,x=c.length;a<x;a++)a in c&&b.call(f,c[a],a,c)}function E(c){g?setTimeout(c,0):K.push(c)}function i(c){try{n.documentElement.doScroll("left")}catch(b){setTimeout(function(){i(c)},1);return}c()}function o(c,b){function f(){var b=c._scrollTop(),f=c._scrollLeft();b===g&&f===I||(g=b,I=f,c.dispatchEvent&&(b=n.createEvent("MouseEvents"),b.initMouseEvent("scroll",!1,!1,m,0,0,0,0,0,!1,!1,!1,!1,0,null),c.dispatchEvent(b)))}if(!p(c))throw c+" is not a DOM element";if(!c._scrollable){c._scrollable=
!0;c.style.overflow="scroll";c._scrollTop=function(b){if("undefined"===typeof b)return d?Math.max(parseInt(-d.y),0):c.scrollTop;!d&&(!w||H)?c.scrollTop=b:E(function(){d.scrollTo(d.x,Math.min(-b,0),1)})};c._scrollLeft=function(b){if("undefined"===typeof b)return d?Math.max(parseInt(-d.x),0):c.scrollLeft;!d&&(!w||H)?c.scrollLeft=b:E(function(){d.scrollTo(Math.min(-b,0),d.y,1)})};if(!b){if(!w)return;if(H){c.style["-webkit-overflow-scrolling"]="touch";return}}var a=n.createElement("div"),x=Array.prototype.slice.call(c.childNodes||
[]);v(x,function(b){b=c.removeChild(b);a.appendChild(b)});c.appendChild(a);var d,g,I;c._iScroll=!0;E(function(){d=new Z(c,{checkDOMChanges:!0,useTransform:!0,useTransition:!0,hScrollbar:!1,vScrollbar:!1,bounce:!!e.ios,onScrollMove:f,onBeforeScrollEnd:f,onScrollEnd:f,onBeforeScrollStart:r})})}}function r(c){for(var b=c.target;1!==b.nodeType;)b=b.parentNode;"SELECT"!==b.tagName&&"INPUT"!==b.tagName&&"TEXTAREA"!==b.tagName&&c.preventDefault()}function D(c){return p(c)&&c._iScroll?c.childNodes[0]:c}var K=
[],g=!1,H=!1,e,a=navigator.userAgent,d,k,L;if(L=/\bCPU.*OS (\d+(_\d+)?)/i.exec(a))d="ios",k=L[1].replace("_",".");else if(L=/\bAndroid (\d+(\.\d+)?)/.exec(a))d="android",k=L[1];a={name:d,version:k&&m.parseFloat(k)};a[d]=!0;e=a;var w=!!e.name,Z;if(e.ios&&5<=e.version||e.android&&4<=e.version)H=!0;var t=m,T=n;d=function(c){if(""===u)return c;c=c.charAt(0).toUpperCase()+c.substr(1);return u+c};var j=Math,a=T.createElement("div").style,u;a:{k=["t","webkitT","MozT","msT","OT"];var l;L=0;for(var U=k.length;L<
U;L++)if(l=k[L]+"ransform",l in a){u=k[L].substr(0,k[L].length-1);break a}u=!1}var A=u?"-"+u.toLowerCase()+"-":"",q=d("transform"),C=d("transitionProperty"),B=d("transitionDuration"),O=d("transformOrigin"),V=d("transitionTimingFunction"),M=d("transitionDelay"),P=/android/gi.test(navigator.appVersion),Q=/iphone|ipad/gi.test(navigator.appVersion);k=/hp-tablet/gi.test(navigator.appVersion);var G=d("perspective")in a,x="ontouchstart"in t&&!k,I=!!u,fa=d("transition")in a,W="onorientationchange"in t?"orientationchange":
"resize",ba=x?"touchstart":"mousedown",y=x?"touchmove":"mousemove",F=x?"touchend":"mouseup",R=x?"touchcancel":"mouseup",N="Moz"==u?"DOMMouseScroll":"mousewheel",J;J=!1===u?!1:{"":"transitionend",webkit:"webkitTransitionEnd",Moz:"transitionend",O:"oTransitionEnd",ms:"MSTransitionEnd"}[u];var ga=t.requestAnimationFrame||t.webkitRequestAnimationFrame||t.mozRequestAnimationFrame||t.oRequestAnimationFrame||t.msRequestAnimationFrame||function(c){return setTimeout(c,1)},X=t.cancelRequestAnimationFrame||
t.webkitCancelAnimationFrame||t.webkitCancelRequestAnimationFrame||t.mozCancelRequestAnimationFrame||t.oCancelRequestAnimationFrame||t.msCancelRequestAnimationFrame||clearTimeout,S=G?" translateZ(0)":"";k=function(c,b){var f=this,a;f.wrapper="object"==typeof c?c:T.getElementById(c);f.wrapper.style.overflow="hidden";f.scroller=f.wrapper.children[0];f.options={hScroll:!0,vScroll:!0,x:0,y:0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,topOffset:0,checkDOMChanges:!1,
handleClick:!0,hScrollbar:!0,vScrollbar:!0,fixedScrollbar:P,hideScrollbar:Q,fadeScrollbar:Q&&G,scrollbarClass:"",zoom:!1,zoomMin:1,zoomMax:4,doubleTapZoom:2,wheelAction:"scroll",snap:!1,snapThreshold:1,onRefresh:null,onBeforeScrollStart:function(b){b.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null,onZoomStart:null,onZoom:null,onZoomEnd:null};for(a in b)f.options[a]=b[a];f.x=f.options.x;f.y=f.options.y;
f.options.useTransform=I&&f.options.useTransform;f.options.hScrollbar=f.options.hScroll&&f.options.hScrollbar;f.options.vScrollbar=f.options.vScroll&&f.options.vScrollbar;f.options.zoom=f.options.useTransform&&f.options.zoom;f.options.useTransition=fa&&f.options.useTransition;f.options.zoom&&P&&(S="");f.scroller.style[C]=f.options.useTransform?A+"transform":"top left";f.scroller.style[B]="0";f.scroller.style[O]="0 0";f.options.useTransition&&(f.scroller.style[V]="cubic-bezier(0.33,0.66,0.66,1)");
f.options.useTransform?f.scroller.style[q]="translate("+f.x+"px,"+f.y+"px)"+S:f.scroller.style.cssText+=";position:absolute;top:"+f.y+"px;left:"+f.x+"px";f.options.useTransition&&(f.options.fixedScrollbar=!0);f.refresh();f._bind(W,t);f._bind(ba);x||(f._bind("mouseout",f.wrapper),"none"!=f.options.wheelAction&&f._bind(N));f.options.checkDOMChanges&&(f.checkDOMTime=setInterval(function(){f._checkDOMChanges()},500))};k.prototype={enabled:!0,x:0,y:0,steps:[],scale:1,currPageX:0,currPageY:0,pagesX:[],
pagesY:[],aniTime:null,wheelZoomCount:0,handleEvent:function(c){switch(c.type){case ba:if(!x&&0!==c.button)break;this._start(c);break;case y:this._move(c);break;case F:case R:this._end(c);break;case W:this._resize();break;case N:this._wheel(c);break;case "mouseout":this._mouseout(c);break;case J:this._transitionEnd(c)}},_checkDOMChanges:function(){!this.moved&&!this.zoomed&&!(this.animating||this.scrollerW==this.scroller.offsetWidth*this.scale&&this.scrollerH==this.scroller.offsetHeight*this.scale)&&
this.refresh()},_scrollbar:function(c){var b;this[c+"Scrollbar"]?(this[c+"ScrollbarWrapper"]||(b=T.createElement("div"),this.options.scrollbarClass?b.className=this.options.scrollbarClass+c.toUpperCase():b.style.cssText="position:absolute;z-index:100;"+("h"==c?"height:7px;bottom:1px;left:2px;right:"+(this.vScrollbar?"7":"2")+"px":"width:7px;bottom:"+(this.hScrollbar?"7":"2")+"px;top:2px;right:1px"),b.style.cssText+=";pointer-events:none;"+A+"transition-property:opacity;"+A+"transition-duration:"+
(this.options.fadeScrollbar?"350ms":"0")+";overflow:hidden;opacity:"+(this.options.hideScrollbar?"0":"1"),this.wrapper.appendChild(b),this[c+"ScrollbarWrapper"]=b,b=T.createElement("div"),this.options.scrollbarClass||(b.style.cssText="position:absolute;z-index:100;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.9);"+A+"background-clip:padding-box;"+A+"box-sizing:border-box;"+("h"==c?"height:100%":"width:100%")+";"+A+"border-radius:3px;border-radius:3px"),b.style.cssText+=";pointer-events:none;"+
A+"transition-property:"+A+"transform;"+A+"transition-timing-function:cubic-bezier(0.33,0.66,0.66,1);"+A+"transition-duration:0;"+A+"transform: translate(0,0)"+S,this.options.useTransition&&(b.style.cssText+=";"+A+"transition-timing-function:cubic-bezier(0.33,0.66,0.66,1)"),this[c+"ScrollbarWrapper"].appendChild(b),this[c+"ScrollbarIndicator"]=b),"h"==c?(this.hScrollbarSize=this.hScrollbarWrapper.clientWidth,this.hScrollbarIndicatorSize=j.max(j.round(this.hScrollbarSize*this.hScrollbarSize/this.scrollerW),
8),this.hScrollbarIndicator.style.width=this.hScrollbarIndicatorSize+"px",this.hScrollbarMaxScroll=this.hScrollbarSize-this.hScrollbarIndicatorSize,this.hScrollbarProp=this.hScrollbarMaxScroll/this.maxScrollX):(this.vScrollbarSize=this.vScrollbarWrapper.clientHeight,this.vScrollbarIndicatorSize=j.max(j.round(this.vScrollbarSize*this.vScrollbarSize/this.scrollerH),8),this.vScrollbarIndicator.style.height=this.vScrollbarIndicatorSize+"px",this.vScrollbarMaxScroll=this.vScrollbarSize-this.vScrollbarIndicatorSize,
this.vScrollbarProp=this.vScrollbarMaxScroll/this.maxScrollY),this._scrollbarPos(c,!0)):this[c+"ScrollbarWrapper"]&&(I&&(this[c+"ScrollbarIndicator"].style[q]=""),this[c+"ScrollbarWrapper"].parentNode.removeChild(this[c+"ScrollbarWrapper"]),this[c+"ScrollbarWrapper"]=null,this[c+"ScrollbarIndicator"]=null)},_resize:function(){var c=this;setTimeout(function(){c.refresh()},P?200:0)},_pos:function(c,b){this.zoomed||(c=this.hScroll?c:0,b=this.vScroll?b:0,this.options.useTransform?this.scroller.style[q]=
"translate("+c+"px,"+b+"px) scale("+this.scale+")"+S:(c=j.round(c),b=j.round(b),this.scroller.style.left=c+"px",this.scroller.style.top=b+"px"),this.x=c,this.y=b,this._scrollbarPos("h"),this._scrollbarPos("v"))},_scrollbarPos:function(c,b){var f="h"==c?this.x:this.y;this[c+"Scrollbar"]&&(f*=this[c+"ScrollbarProp"],0>f?(this.options.fixedScrollbar||(f=this[c+"ScrollbarIndicatorSize"]+j.round(3*f),8>f&&(f=8),this[c+"ScrollbarIndicator"].style["h"==c?"width":"height"]=f+"px"),f=0):f>this[c+"ScrollbarMaxScroll"]&&
(this.options.fixedScrollbar?f=this[c+"ScrollbarMaxScroll"]:(f=this[c+"ScrollbarIndicatorSize"]-j.round(3*(f-this[c+"ScrollbarMaxScroll"])),8>f&&(f=8),this[c+"ScrollbarIndicator"].style["h"==c?"width":"height"]=f+"px",f=this[c+"ScrollbarMaxScroll"]+(this[c+"ScrollbarIndicatorSize"]-f))),this[c+"ScrollbarWrapper"].style[M]="0",this[c+"ScrollbarWrapper"].style.opacity=b&&this.options.hideScrollbar?"0":"1",this[c+"ScrollbarIndicator"].style[q]="translate("+("h"==c?f+"px,0)":"0,"+f+"px)")+S)},_start:function(c){var b=
x?c.touches[0]:c,f,a;if(this.enabled){this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,c);(this.options.useTransition||this.options.zoom)&&this._transitionTime(0);this.zoomed=this.animating=this.moved=!1;this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0;this.options.zoom&&x&&1<c.touches.length&&(a=j.abs(c.touches[0].pageX-c.touches[1].pageX),f=j.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDistStart=j.sqrt(a*a+f*f),this.originX=j.abs(c.touches[0].pageX+
c.touches[1].pageX-2*this.wrapperOffsetLeft)/2-this.x,this.originY=j.abs(c.touches[0].pageY+c.touches[1].pageY-2*this.wrapperOffsetTop)/2-this.y,this.options.onZoomStart&&this.options.onZoomStart.call(this,c));if(this.options.momentum&&(this.options.useTransform?(f=getComputedStyle(this.scroller,null)[q].replace(/[^0-9\-.,]/g,"").split(","),a=1*f[4],f=1*f[5]):(a=1*getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,""),f=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),
a!=this.x||f!=this.y))this.options.useTransition?this._unbind(J):X(this.aniTime),this.steps=[],this._pos(a,f);this.absStartX=this.x;this.absStartY=this.y;this.startX=this.x;this.startY=this.y;this.pointX=b.pageX;this.pointY=b.pageY;this.startTime=c.timeStamp||Date.now();this.options.onScrollStart&&this.options.onScrollStart.call(this,c);this._bind(y);this._bind(F);this._bind(R)}},_move:function(c){var b=x?c.touches[0]:c,f=b.pageX-this.pointX,a=b.pageY-this.pointY,e=this.x+f,d=this.y+a,g=c.timeStamp||
Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,c);if(this.options.zoom&&x&&1<c.touches.length)e=j.abs(c.touches[0].pageX-c.touches[1].pageX),d=j.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDist=j.sqrt(e*e+d*d),this.zoomed=!0,b=1/this.touchesDistStart*this.touchesDist*this.scale,b<this.options.zoomMin?b=0.5*this.options.zoomMin*Math.pow(2,b/this.options.zoomMin):b>this.options.zoomMax&&(b=2*this.options.zoomMax*Math.pow(0.5,this.options.zoomMax/b)),
this.lastScale=b/this.scale,e=this.originX-this.originX*this.lastScale+this.x,d=this.originY-this.originY*this.lastScale+this.y,this.scroller.style[q]="translate("+e+"px,"+d+"px) scale("+b+")"+S,this.options.onZoom&&this.options.onZoom.call(this,c);else{this.pointX=b.pageX;this.pointY=b.pageY;if(0<e||e<this.maxScrollX)e=this.options.bounce?this.x+f/2:0<=e||0<=this.maxScrollX?0:this.maxScrollX;if(d>this.minScrollY||d<this.maxScrollY)d=this.options.bounce?this.y+a/2:d>=this.minScrollY||0<=this.maxScrollY?
this.minScrollY:this.maxScrollY;this.distX+=f;this.distY+=a;this.absDistX=j.abs(this.distX);this.absDistY=j.abs(this.distY);6>this.absDistX&&6>this.absDistY||(this.options.lockDirection&&(this.absDistX>this.absDistY+5?(d=this.y,a=0):this.absDistY>this.absDistX+5&&(e=this.x,f=0)),this.moved=!0,this._pos(e,d),this.dirX=0<f?-1:0>f?1:0,this.dirY=0<a?-1:0>a?1:0,300<g-this.startTime&&(this.startTime=g,this.startX=this.x,this.startY=this.y),this.options.onScrollMove&&this.options.onScrollMove.call(this,
c))}},_end:function(c){if(!(x&&0!==c.touches.length)){var b=this,f=x?c.changedTouches[0]:c,a,e,d={dist:0,time:0},g={dist:0,time:0},I=(c.timeStamp||Date.now())-b.startTime,h=b.x,i=b.y;b._unbind(y);b._unbind(F);b._unbind(R);b.options.onBeforeScrollEnd&&b.options.onBeforeScrollEnd.call(b,c);if(b.zoomed)h=b.scale*b.lastScale,h=Math.max(b.options.zoomMin,h),h=Math.min(b.options.zoomMax,h),b.lastScale=h/b.scale,b.scale=h,b.x=b.originX-b.originX*b.lastScale+b.x,b.y=b.originY-b.originY*b.lastScale+b.y,b.scroller.style[B]=
"200ms",b.scroller.style[q]="translate("+b.x+"px,"+b.y+"px) scale("+b.scale+")"+S,b.zoomed=!1,b.refresh(),b.options.onZoomEnd&&b.options.onZoomEnd.call(b,c);else{if(b.moved){if(300>I&&b.options.momentum){d=h?b._momentum(h-b.startX,I,-b.x,b.scrollerW-b.wrapperW+b.x,b.options.bounce?b.wrapperW:0):d;g=i?b._momentum(i-b.startY,I,-b.y,0>b.maxScrollY?b.scrollerH-b.wrapperH+b.y-b.minScrollY:0,b.options.bounce?b.wrapperH:0):g;h=b.x+d.dist;i=b.y+g.dist;if(0<b.x&&0<h||b.x<b.maxScrollX&&h<b.maxScrollX)d={dist:0,
time:0};if(b.y>b.minScrollY&&i>b.minScrollY||b.y<b.maxScrollY&&i<b.maxScrollY)g={dist:0,time:0}}d.dist||g.dist?(d=j.max(j.max(d.time,g.time),10),b.options.snap&&(g=h-b.absStartX,I=i-b.absStartY,j.abs(g)<b.options.snapThreshold&&j.abs(I)<b.options.snapThreshold?b.scrollTo(b.absStartX,b.absStartY,200):(g=b._snap(h,i),h=g.x,i=g.y,d=j.max(g.time,d))),b.scrollTo(j.round(h),j.round(i),d)):b.options.snap?(g=h-b.absStartX,I=i-b.absStartY,j.abs(g)<b.options.snapThreshold&&j.abs(I)<b.options.snapThreshold?
b.scrollTo(b.absStartX,b.absStartY,200):(g=b._snap(b.x,b.y),(g.x!=b.x||g.y!=b.y)&&b.scrollTo(g.x,g.y,g.time))):b._resetPos(200)}else x&&(b.doubleTapTimer&&b.options.zoom?(clearTimeout(b.doubleTapTimer),b.doubleTapTimer=null,b.options.onZoomStart&&b.options.onZoomStart.call(b,c),b.zoom(b.pointX,b.pointY,1==b.scale?b.options.doubleTapZoom:1),b.options.onZoomEnd&&setTimeout(function(){b.options.onZoomEnd.call(b,c)},200)):this.options.handleClick&&(b.doubleTapTimer=setTimeout(function(){b.doubleTapTimer=
null;for(a=f.target;1!=a.nodeType;)a=a.parentNode;"SELECT"!=a.tagName&&"INPUT"!=a.tagName&&"TEXTAREA"!=a.tagName&&(e=T.createEvent("MouseEvents"),e.initMouseEvent("click",!0,!0,c.view,1,f.screenX,f.screenY,f.clientX,f.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null),e._fake=!0,a.dispatchEvent(e))},b.options.zoom?250:0))),b._resetPos(200);b.options.onTouchEnd&&b.options.onTouchEnd.call(b,c)}}},_resetPos:function(c){var b=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,f=this.y>=this.minScrollY||
0<this.maxScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:this.y;if(b==this.x&&f==this.y){if(this.moved&&(this.moved=!1,this.options.onScrollEnd&&this.options.onScrollEnd.call(this)),this.hScrollbar&&this.options.hideScrollbar&&("webkit"==u&&(this.hScrollbarWrapper.style[M]="300ms"),this.hScrollbarWrapper.style.opacity="0"),this.vScrollbar&&this.options.hideScrollbar)"webkit"==u&&(this.vScrollbarWrapper.style[M]="300ms"),this.vScrollbarWrapper.style.opacity="0"}else this.scrollTo(b,
f,c||0)},_wheel:function(c){var b=this,f,a;if("wheelDeltaX"in c)f=c.wheelDeltaX/12,a=c.wheelDeltaY/12;else if("wheelDelta"in c)f=a=c.wheelDelta/12;else if("detail"in c)f=a=3*-c.detail;else return;if("zoom"==b.options.wheelAction){if(a=b.scale*Math.pow(2,1/3*(a?a/Math.abs(a):0)),a<b.options.zoomMin&&(a=b.options.zoomMin),a>b.options.zoomMax&&(a=b.options.zoomMax),a!=b.scale)!b.wheelZoomCount&&b.options.onZoomStart&&b.options.onZoomStart.call(b,c),b.wheelZoomCount++,b.zoom(c.pageX,c.pageY,a,400),setTimeout(function(){b.wheelZoomCount--;
!b.wheelZoomCount&&b.options.onZoomEnd&&b.options.onZoomEnd.call(b,c)},400)}else f=b.x+f,a=b.y+a,0<f?f=0:f<b.maxScrollX&&(f=b.maxScrollX),a>b.minScrollY?a=b.minScrollY:a<b.maxScrollY&&(a=b.maxScrollY),0>b.maxScrollY&&b.scrollTo(f,a,0)},_mouseout:function(c){var b=c.relatedTarget;if(b)for(;b=b.parentNode;)if(b==this.wrapper)return;this._end(c)},_transitionEnd:function(c){c.target==this.scroller&&(this._unbind(J),this._startAni())},_startAni:function(){var c=this,b=c.x,f=c.y,a=Date.now(),d,e,x;c.animating||
(c.steps.length?(d=c.steps.shift(),d.x==b&&d.y==f&&(d.time=0),c.animating=!0,c.moved=!0,c.options.useTransition)?(c._transitionTime(d.time),c._pos(d.x,d.y),c.animating=!1,d.time?c._bind(J):c._resetPos(0)):(x=function(){var g=Date.now(),h;g>=a+d.time?(c._pos(d.x,d.y),c.animating=!1,c.options.onAnimationEnd&&c.options.onAnimationEnd.call(c),c._startAni()):(g=(g-a)/d.time-1,e=j.sqrt(1-g*g),g=(d.x-b)*e+b,h=(d.y-f)*e+f,c._pos(g,h),c.animating&&(c.aniTime=ga(x)))},x()):c._resetPos(400))},_transitionTime:function(c){c+=
"ms";this.scroller.style[B]=c;this.hScrollbar&&(this.hScrollbarIndicator.style[B]=c);this.vScrollbar&&(this.vScrollbarIndicator.style[B]=c)},_momentum:function(c,b,f,a,d){var b=j.abs(c)/b,e=b*b/0.0012;0<c&&e>f?(f+=d/(6/(6E-4*(e/b))),b=b*f/e,e=f):0>c&&e>a&&(a+=d/(6/(6E-4*(e/b))),b=b*a/e,e=a);return{dist:e*(0>c?-1:1),time:j.round(b/6E-4)}},_offset:function(c){for(var b=-c.offsetLeft,f=-c.offsetTop;c=c.offsetParent;)b-=c.offsetLeft,f-=c.offsetTop;c!=this.wrapper&&(b*=this.scale,f*=this.scale);return{left:b,
top:f}},_snap:function(c,b){var f,a,d;d=this.pagesX.length-1;f=0;for(a=this.pagesX.length;f<a;f++)if(c>=this.pagesX[f]){d=f;break}d==this.currPageX&&0<d&&0>this.dirX&&d--;c=this.pagesX[d];a=(a=j.abs(c-this.pagesX[this.currPageX]))?500*(j.abs(this.x-c)/a):0;this.currPageX=d;d=this.pagesY.length-1;for(f=0;f<d;f++)if(b>=this.pagesY[f]){d=f;break}d==this.currPageY&&0<d&&0>this.dirY&&d--;b=this.pagesY[d];f=(f=j.abs(b-this.pagesY[this.currPageY]))?500*(j.abs(this.y-b)/f):0;this.currPageY=d;d=j.round(j.max(a,
f))||200;return{x:c,y:b,time:d}},_bind:function(c,b,a){(b||this.scroller).addEventListener(c,this,!!a)},_unbind:function(c,b,a){(b||this.scroller).removeEventListener(c,this,!!a)},destroy:function(){this.scroller.style[q]="";this.vScrollbar=this.hScrollbar=!1;this._scrollbar("h");this._scrollbar("v");this._unbind(W,t);this._unbind(ba);this._unbind(y);this._unbind(F);this._unbind(R);this.options.hasTouch||(this._unbind("mouseout",this.wrapper),this._unbind(N));this.options.useTransition&&this._unbind(J);
this.options.checkDOMChanges&&clearInterval(this.checkDOMTime);this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var c,b,a,d=0;b=0;this.scale<this.options.zoomMin&&(this.scale=this.options.zoomMin);this.wrapperW=this.wrapper.clientWidth||1;this.wrapperH=this.wrapper.clientHeight||1;this.minScrollY=-this.options.topOffset||0;this.scrollerW=j.round(this.scroller.offsetWidth*this.scale);this.scrollerH=j.round((this.scroller.offsetHeight+this.minScrollY)*this.scale);this.maxScrollX=
this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH+this.minScrollY;this.dirY=this.dirX=0;this.options.onRefresh&&this.options.onRefresh.call(this);this.hScroll=this.options.hScroll&&0>this.maxScrollX;this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);this.hScrollbar=this.hScroll&&this.options.hScrollbar;this.vScrollbar=this.vScroll&&this.options.vScrollbar&&this.scrollerH>this.wrapperH;c=this._offset(this.wrapper);this.wrapperOffsetLeft=
-c.left;this.wrapperOffsetTop=-c.top;if("string"==typeof this.options.snap){this.pagesX=[];this.pagesY=[];a=this.scroller.querySelectorAll(this.options.snap);c=0;for(b=a.length;c<b;c++)d=this._offset(a[c]),d.left+=this.wrapperOffsetLeft,d.top+=this.wrapperOffsetTop,this.pagesX[c]=d.left<this.maxScrollX?this.maxScrollX:d.left*this.scale,this.pagesY[c]=d.top<this.maxScrollY?this.maxScrollY:d.top*this.scale}else if(this.options.snap){for(this.pagesX=[];d>=this.maxScrollX;)this.pagesX[b]=d,d-=this.wrapperW,
b++;this.maxScrollX%this.wrapperW&&(this.pagesX[this.pagesX.length]=this.maxScrollX-this.pagesX[this.pagesX.length-1]+this.pagesX[this.pagesX.length-1]);b=d=0;for(this.pagesY=[];d>=this.maxScrollY;)this.pagesY[b]=d,d-=this.wrapperH,b++;this.maxScrollY%this.wrapperH&&(this.pagesY[this.pagesY.length]=this.maxScrollY-this.pagesY[this.pagesY.length-1]+this.pagesY[this.pagesY.length-1])}this._scrollbar("h");this._scrollbar("v");this.zoomed||(this.scroller.style[B]="0",this._resetPos(200))},scrollTo:function(c,
b,a,d){var e=c;this.stop();e.length||(e=[{x:c,y:b,time:a,relative:d}]);c=0;for(b=e.length;c<b;c++)e[c].relative&&(e[c].x=this.x-e[c].x,e[c].y=this.y-e[c].y),this.steps.push({x:e[c].x,y:e[c].y,time:e[c].time||0});this._startAni()},scrollToElement:function(c,b){var a;if(c=c.nodeType?c:this.scroller.querySelector(c))a=this._offset(c),a.left+=this.wrapperOffsetLeft,a.top+=this.wrapperOffsetTop,a.left=0<a.left?0:a.left<this.maxScrollX?this.maxScrollX:a.left,a.top=a.top>this.minScrollY?this.minScrollY:
a.top<this.maxScrollY?this.maxScrollY:a.top,b=void 0===b?j.max(2*j.abs(a.left),2*j.abs(a.top)):b,this.scrollTo(a.left,a.top,b)},scrollToPage:function(c,b,a){a=void 0===a?400:a;this.options.onScrollStart&&this.options.onScrollStart.call(this);if(this.options.snap)c="next"==c?this.currPageX+1:"prev"==c?this.currPageX-1:c,b="next"==b?this.currPageY+1:"prev"==b?this.currPageY-1:b,c=0>c?0:c>this.pagesX.length-1?this.pagesX.length-1:c,b=0>b?0:b>this.pagesY.length-1?this.pagesY.length-1:b,this.currPageX=
c,this.currPageY=b,c=this.pagesX[c],b=this.pagesY[b];else if(c*=-this.wrapperW,b*=-this.wrapperH,c<this.maxScrollX&&(c=this.maxScrollX),b<this.maxScrollY)b=this.maxScrollY;this.scrollTo(c,b,a)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(y);this._unbind(F);this._unbind(R)},enable:function(){this.enabled=!0},stop:function(){this.options.useTransition?this._unbind(J):X(this.aniTime);this.steps=[];this.animating=this.moved=!1},zoom:function(c,b,a,d){var e=a/this.scale;
this.options.useTransform&&(this.zoomed=!0,d=void 0===d?200:d,c=c-this.wrapperOffsetLeft-this.x,b=b-this.wrapperOffsetTop-this.y,this.x=c-c*e+this.x,this.y=b-b*e+this.y,this.scale=a,this.refresh(),this.x=0<this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,this.y=this.y>this.minScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:this.y,this.scroller.style[B]=d+"ms",this.scroller.style[q]="translate("+this.x+"px,"+this.y+"px) scale("+a+")"+S,this.zoomed=!1)},isReady:function(){return!this.moved&&
!this.zoomed&&!this.animating}};a=null;Z=k;var Y=function(){g||(g=!0,v(K,function(c){setTimeout(c,0)}))};if("complete"===n.readyState)setTimeout(Y,0);else if(n.addEventListener)n.addEventListener("DOMContentLoaded",Y,!1),m.addEventListener("load",Y,!1);else if(n.attachEvent){n.attachEvent("onreadystatechange",Y);m.attachEvent("onload",Y);l=!1;try{l=null===m.frameElement}catch(ha){}n.documentElement.doScroll&&l&&setTimeout(function(){i(Y)},0)}l=function(){o.apply(this,arguments)};d=function(){o.apply(this,
arguments)};z&&(d.node=function(){return D.apply(this,arguments)},z.plugin("scrollable",d));if(h){h.extend(h.fn,{scrollable:function(c){this.forEach(function(b){o(b,c)});return this},scrollableNode:function(){return $(this.map(function(){return D(this)}))}});var aa=h.fn.scrollTop,ca=h.fn.scrollLeft;h.fn.scrollTop=function(c){if("undefined"===typeof c){var b=this[0],a=p(b);return a&&b._scrollTop?b._scrollTop():aa?aa.apply(this,arguments):a?b.scrollTop:null}this.forEach(function(b){var a=p(b);a&&b._scrollTop?
b._scrollTop(c):aa?aa.call(h(b),c):a&&(b.scrollTop=c)});return this};h.fn.scrollLeft=function(c){if("undefined"===typeof c){var b=this[0],a=p(b);return a&&b._scrollLeft?b._scrollLeft():aa?ca.apply(this,arguments):a?b.scrollLeft:null}this.forEach(function(b){var a=p(b);a&&b._scrollLeft?b._scrollLeft(c):ca?ca.call(h(b),c):a&&(b.scrollLeft=c)});return this}}if(s){s.fn.scrollable=function(c){this.each(function(){o(this,c)});return this};s.fn.scrollableNode=function(){return $(this.map(function(){return D(this)}))};
var da=s.fn.scrollTop,ea=s.fn.scrollLeft;s.fn.scrollTop=function(c){if("undefined"===typeof c){var b=this[0];return p(b)&&b._scrollTop?b._scrollTop():da.apply(this,arguments)}this.each(function(){p(this)&&this._scrollTop?this._scrollTop(c):da.call(s(this),c)});return this};s.fn.scrollLeft=function(c){if("undefined"===typeof c){var b=this[0];return p(b)&&b._scrollLeft?b._scrollLeft():ea.apply(this,arguments)}this.each(function(){p(this)&&this._scrollLeft?this._scrollLeft(c):ea.call(s(this),c)});return this}}l.node=
function(){return D.apply(this,arguments)};return l}(window,document,window.clik,window.Zepto,window.jQuery);
(function(m,n,z,h,s,p,v){function E(a,e){e?a.setAttribute(d,e):e=a.getAttribute(d);"string"===typeof e&&0!==e.length&&(a.parentNode.removeChild(a),U[e]=a.cloneNode(!0))}function i(a,d){a.addEventListener("click",function(){function e(){g||(g=!0,a.disabled=!1,a.className=a.className.replace(RegExp("\\b"+h+"\\b","g"),""))}var g=!1,h=a.getAttribute("data-clickable-class")||"active",i;a.disabled=!0;a.className+=" "+h;try{i=d(e)}catch(j){e()}!1===i&&e()},!1)}function o(d,g,h,W){function m(){var a=N;Array.prototype.forEach.call(a.querySelectorAll(".app-content"),
function(a){a.getAttribute("data-no-scroll")||p(a)});Array.prototype.forEach.call(a.querySelectorAll("[data-scrollable]"),function(a){p(a)});B=!1;setTimeout(D,0);W()}if(B){if(+new Date>B+Z){C.push(["load",d,g,h,W]);return}return!1}B=+new Date;if(!Q){for(var y=n.getElementsByClassName(a),F=y.length;F--;)E(y[F]);if(y=/\bCPU.*OS (\d+(_\d+)?)/i.exec(navigator.userAgent))O="ios",V=parseFloat(y[1]),n.body.className+=" "+k,M=t,P=u[M];else if(y=/\bAndroid (\d+(\.\d+)?)/.exec(navigator.userAgent))O="android",
V=parseFloat(y[1]),n.body.className+=" "+L,M=4<=V?T:j,P=u[M];l.platform=O;l.platformVersion=V;n.body.className+=" "+w}var R={},N;if(!(d in U))throw TypeError(d+" is not a known page");var J=U[d].cloneNode(!0),y=A[d]||[];e(J);Array.prototype.forEach.call(J.querySelectorAll(".app-button"),function(a){s(a);var d=a.getAttribute("data-target");a.getAttribute("data-back")?i(a,function(a){return r({},a)}):d&&i(a,function(a){return o(d,{},{},a)})});y.forEach(function(a){a[0].call(R,J,g)});Array.prototype.forEach.call(J.querySelectorAll("img"),
function(a){if(a.getAttribute("data-auto-load")){var d="android"===O?400:0,e=a.src;a.src="";z(a,e,d)}});N=J;if(Q){y=G;if((F=H(y))&&!F._iScroll)F=F._scrollTop(),(y||G).setAttribute("data-last-scroll",F+"");y=G;if((F=H(y))&&!F._iScroll){var v=F.style["-webkit-overflow-scrolling"]||"";F.style["-webkit-overflow-scrolling"]="";(y||G).setAttribute("data-scroll-style",v)}var y={},X;for(X in h)y[X]=h[X];K(N,y,m)}else n.body.appendChild(N),setTimeout(m,0);Q=d;G=N;q.push([d,N,h,g,R])}function r(a,d){if(B){if(+new Date>
B+Z){C.push(["back",a,d]);return}return!1}if(2>q.length)throw Error("navigation stack is empty");B=+new Date;var g=q.pop(),h=q[q.length-1],i=h[0],j=h[1],h=g[2];e(j);Array.prototype.forEach.call(g[1].querySelectorAll("*"),function(a){a.style["-webkit-overflow-scrolling"]=""});var l=H(j);if(l&&!l._iScroll){var n=parseInt((j||G).getAttribute("data-last-scroll"));n&&l._scrollTop(n)}var l={},k;for(k in h)l[k]=h[k];for(k in a)l[k]=a[k];K(j,l,function(){var a=H(j);if(a&&!a._iScroll){var e=(j||G).getAttribute("data-scroll-style")||
"";a.style["-webkit-overflow-scrolling"]=e}setTimeout(D,0);var a=g[0],h=g[1],x=g[3],i=g[4];if(!(a in U))throw TypeError(a+" is not a known page");(A[a]||[]).forEach(function(a){a[1].call(i,h,x)});B=!1;d()},!0);Q=i;G=j}function D(){if(0!==C.length){var a=C.shift();switch(a.shift()){case "load":o.apply(m,a);break;case "back":r.apply(m,a)}}}function K(a,d,e,i){function j(){n.body.removeChild(k);e()}function l(){--A||(B(),c(),b(),m.appendChild(o),a.appendChild(t),h(m,a,"instant"),j())}var k=n.createElement("div");
k.className="app-clickblocker";n.body.appendChild(k);var m=G;if(d.transition)i&&(d.transition=u[d.transition]||d.transition),h(m,a,d,j);else if(d.transition=i?P:M,"ios"!==O||"slide-left"!==d.transition&&"slide-right"!==d.transition)h(m,a,d,j);else{var i=m.querySelector(".app-topbar"),o=m.querySelector(".app-content"),p=m.querySelector(".app-topbar .app-title"),q=m.querySelector(".app-topbar .left.app-button"),s=m.querySelector(".app-topbar .right.app-button"),r=a.querySelector(".app-topbar"),t=a.querySelector(".app-content"),
v=a.querySelector(".app-topbar .app-title"),w=a.querySelector(".app-topbar .left.app-button"),z=a.querySelector(".app-topbar .right.app-button");if(!i||!r||!o||!t)h(m,a,d,j);else{var A=4,B=g(i,r,p,v,d,l),c=g(i,r,q,w,d,l),b=g(i,r,s,z,d,l);h(o,t,d,l)}}}function g(a,d,e,g,i,j){var l=function(){};if(e&&g)h(e,g,{easing:i.easing,duration:i.duration,transition:"fade"},j),l=function(){a.appendChild(e);d.appendChild(g)};else if(e){var k=n.createElement("div");k.className=e.className;k.innerHTML=e.innerHTML;
k.style.visibility="hidden";h(e,k,{easing:i.easing,duration:i.duration,transition:"fade"},j);l=function(){a.removeChild(k);a.appendChild(e)}}else g?(k=n.createElement("div"),k.className=g.className,k.innerHTML=g.innerHTML,k.style.visibility="hidden",a.appendChild(k),h(k,g,{easing:i.easing,duration:i.duration,transition:"fade"},j),l=function(){d.appendChild(g)}):setTimeout(j,0);return l}function H(a){if(a=a||G)if((a=a.querySelector(".app-content"))&&a._scrollable)return a}function e(a){var d=a.querySelector(".app-topbar");
if(a=a.querySelector(".app-content")){var e=m.innerHeight;if(d){var d=n.defaultView.getComputedStyle(d,null),g="android"===O?48:44;d.height&&(g=parseInt(d.height)||0);a.style.height=e-g+"px"}else a.style.height=e+"px"}}var a="app-page",d="data-page",k="app-ios",L="app-android",w="app-loaded",Z=300,t="slide-left",T="implode-out",j="fade-on",u={fade:"fade","fade-on":"fade-off","fade-off":"fade-on","scale-in":"scale-out","scale-out":"scale-in","rotate-left":"rotate-right","rotate-right":"rotate-left",
"cube-left":"cube-right","cube-right":"cube-left","swap-left":"swap-right","swap-right":"swap-left","explode-in":"explode-out","explode-out":"explode-in","implode-in":"implode-out","implode-out":"implode-in","slide-left":"slide-right","slide-right":"slide-left","slide-up":"slide-down","slide-down":"slide-up","slideon-left":"slideoff-left","slideon-right":"slideoff-right","slideon-up":"slideoff-up","slideon-down":"slideoff-down","slideoff-left":"slideon-left","slideoff-right":"slideon-right","slideoff-up":"slideon-up",
"slideoff-down":"slideon-down"},l={},U={},A={},q=[],C=[],B=!1,O,V,M,P,Q,G;l.platform=null;l.platformVersion=null;l.current=function(){return Q};l.add=function(a,d){"string"!==typeof a&&(d=a,a=void 0);var e;a:if(d){try{e=d instanceof Node||d instanceof HTMLElement;break a}catch(g){}e="object"!==typeof d||"number"!==typeof d.nodeType||"string"!==typeof d.nodeName?!1:!0}else e=!1;if(!e)throw TypeError("page template node must be a DOM node, got "+d);E(d,a)};l.populator=function(a,d,e){if("string"!==
typeof a)throw TypeError("page name must be a string, got "+a);if("function"!==typeof d)throw TypeError("page populator must be a function, got "+d);switch(typeof e){case "undefined":e=function(){};break;case "function":break;default:throw TypeError("page unpopulator must be a function, got "+e);}A[a]||(A[a]=[]);A[a].push([d,e])};l.load=function(a,d,e,g){if("string"!==typeof a)throw TypeError("page name must be a string, got "+a);switch(typeof d){case "function":g=d;d={};e={};break;case "undefined":d=
{};break;case "string":e=d;d={};break;case "object":break;default:throw TypeError("page arguments must be an object if defined, got "+d);}switch(typeof e){case "function":g=e;e={};break;case "undefined":e={};break;case "string":e={transition:e};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+e);}switch(typeof g){case "undefined":g=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+g);}o(a,d,
e,g)};l.back=function(a,d){switch(typeof a){case "function":d=a;a={};break;case "undefined":a={};break;case "object":break;default:throw TypeError("options must be an object if defined, got "+a);}switch(typeof d){case "undefined":d=function(){};break;case "function":break;default:throw TypeError("callback must be a function if defined, got "+d);}r(a,d)};l.setDefaultTransition=function(a){if(!(a in u))throw TypeError("invalid transition type, got "+a);M=a;P=u[M]};m.addEventListener("resize",function(){G&&
e(G)});v&&(v.plugin&&v.plugin.back)&&v.plugin.back(function(){if(1<q.length)return l.back(),!1});m.App=l})(window,document,ImageLoader,Swapper,Clickable,Scrollable,window.clik);
